/**
 * fleet-migration :: Phase 6b — Migration Plan & Compatibility Mapping
 *
 * Optional for greenfield work, required for anything replacing an existing
 * system. Each phase names what it retires, how it coexists with the old
 * contract, and how a rollback would work.
 *
 * Commands: /fleet:migration /fleet:compat
 * Tools:    fleet_add_migration_phase, fleet_add_compat_mapping, fleet_list_migration
 *
 * Usage: pi -e extensions/fleet-migration.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import {
  MIG_FILE, archPath, ensureArchDir, loadState, saveState, audit, phaseBrief, aborted, ABORTED_RESULT } from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface MigrationPhase {
  id: string;
  name: string;
  order: number;
  description: string;
  oldComponents: string[];
  newComponents: string[];
  compatibilityLayer: string;
  validationCriteria: string;
  rollbackPlan: string;
  status: "planned" | "in-progress" | "completed";
  coexistenceDuration: string;
  consumerMigrationStrategy: string;
  retirementCondition: string;
}

export interface CompatibilityMapping {
  id: string;
  name: string;
  oldContract: string;
  newContract: string;
  mappingDescription: string;
  bidirectional: boolean;
  verificationStrategy: string;
}

// ─── Operations ──────────────────────────────────────────────────────────────

function phases(state: FleetState): MigrationPhase[] {
  if (!state.migrationPhases) state.migrationPhases = [];
  return state.migrationPhases as MigrationPhase[];
}

function mappings(state: FleetState): CompatibilityMapping[] {
  if (!state.compatMappings) state.compatMappings = [];
  return state.compatMappings as CompatibilityMapping[];
}

export function addMigrationPhase(state: FleetState, input: Partial<MigrationPhase>) {
  const list = phases(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.rollbackPlan?.trim()) {
    return { ok: false, message: "rollbackPlan is required — a migration without a rollback is a bet, not a plan" };
  }

  const id = input.id?.trim() || `MIG-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((m) => m.id === id)) return { ok: false, message: `${id} already exists` };

  const order = input.order ?? list.length + 1;
  const clash = list.find((m) => m.order === order);
  if (clash) return { ok: false, message: `Order ${order} is taken by ${clash.id}` };

  const p: MigrationPhase = {
    id,
    name: input.name.trim(),
    order,
    description: input.description?.trim() || "",
    oldComponents: input.oldComponents || [],
    newComponents: input.newComponents || [],
    compatibilityLayer: input.compatibilityLayer?.trim() || "",
    validationCriteria: input.validationCriteria?.trim() || "",
    rollbackPlan: input.rollbackPlan!.trim(),
    status: "planned",
    coexistenceDuration: input.coexistenceDuration?.trim() || "",
    consumerMigrationStrategy: input.consumerMigrationStrategy?.trim() || "",
    retirementCondition: input.retirementCondition?.trim() || "",
  };
  list.push(p);
  list.sort((a, b) => a.order - b.order);
  saveState(state);
  writeMigrationFile(state);
  audit(`migration phase ${id} order ${order}`, state);
  return { ok: true, message: `${id} planned at order ${order}` };
}

export function addCompatMapping(state: FleetState, input: Partial<CompatibilityMapping>) {
  const list = mappings(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.oldContract?.trim() || !input.newContract?.trim()) {
    return { ok: false, message: "both oldContract and newContract are required" };
  }

  const id = input.id?.trim() || `CMP-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((m) => m.id === id)) return { ok: false, message: `${id} already exists` };

  const m: CompatibilityMapping = {
    id,
    name: input.name.trim(),
    oldContract: input.oldContract.trim(),
    newContract: input.newContract.trim(),
    mappingDescription: input.mappingDescription?.trim() || "",
    bidirectional: input.bidirectional === true,
    verificationStrategy: input.verificationStrategy?.trim() || "",
  };
  list.push(m);
  saveState(state);
  writeMigrationFile(state);
  audit(`compatibility mapping ${id}`, state);
  return { ok: true, message: `${id} maps ${m.oldContract} → ${m.newContract}` };
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeMigrationFile(state: FleetState) {
  ensureArchDir();
  const p = phases(state);
  const c = mappings(state);
  if (p.length === 0 && c.length === 0) {
    writeFileSync(archPath(MIG_FILE), "# Migration Plan\n\n*No migration planned.*\n", "utf8");
    return;
  }
  const lines = ["# Migration Plan", "", `*Generated by fleet-migration · ${new Date().toISOString()}*`, ""];

  if (p.length > 0) {
    lines.push("| Order | ID | Name | Status | Rollback |", "|---|---|---|---|---|");
    for (const x of p) lines.push(`| ${x.order} | ${x.id} | ${x.name} | ${x.status} | ${x.rollbackPlan ? "✅" : "❌"} |`);
    lines.push("", "---", "");
    for (const x of p) {
      lines.push(`## ${x.id} — ${x.name}`);
      lines.push("");
      lines.push(`**Order:** ${x.order}  **Status:** ${x.status}`);
      lines.push("");
      lines.push(x.description || "_unspecified_");
      lines.push("");
      for (const [heading, values] of [["Old Components", x.oldComponents], ["New Components", x.newComponents]] as const) {
        lines.push(`### ${heading}`);
        if (values.length) for (const v of values) lines.push(`- ${v}`);
        else lines.push("_none_");
        lines.push("");
      }
      lines.push(`**Compatibility Layer:** ${x.compatibilityLayer || "—"}`);
      lines.push("");
      lines.push(`**Validation Criteria:** ${x.validationCriteria || "—"}`);
      lines.push("");
      lines.push("### Rollback Plan");
      lines.push(x.rollbackPlan);
      lines.push("");
      lines.push(`**Coexistence Duration:** ${x.coexistenceDuration || "—"}`);
      lines.push(`**Consumer Migration:** ${x.consumerMigrationStrategy || "—"}`);
      lines.push(`**Retirement Condition:** ${x.retirementCondition || "—"}`);
      lines.push("");
      lines.push("---", "");
    }
  }

  if (c.length > 0) {
    lines.push("## Compatibility Mappings", "");
    lines.push("| ID | Name | Old | New | Bidirectional |", "|---|---|---|---|---|");
    for (const x of c) lines.push(`| ${x.id} | ${x.name} | ${x.oldContract} | ${x.newContract} | ${x.bidirectional ? "yes" : "no"} |`);
    lines.push("");
    for (const x of c) {
      lines.push(`## ${x.id} — ${x.name}`);
      lines.push("");
      lines.push(`**Old Contract:** ${x.oldContract}`);
      lines.push(`**New Contract:** ${x.newContract}`);
      lines.push("");
      lines.push(x.mappingDescription || "_unspecified_");
      lines.push("");
      lines.push(`**Verification Strategy:** ${x.verificationStrategy || "—"}`);
      lines.push("");
      lines.push("---", "");
    }
  }
  writeFileSync(archPath(MIG_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:migration", {
    description: "Define a migration plan (Phase 6b) — optional for greenfield",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Phase name (blank to finish)", "");
        if (!name) break;
        const desc = await ctx.ui.input("Description", "");
        const rollback = await ctx.ui.input("Rollback plan", "");
        const validation = await ctx.ui.input("Validation criteria", "");
        const res = addMigrationPhase(state, { name, description: desc, rollbackPlan: rollback, validationCriteria: validation });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerCommand("fleet:compat", {
    description: "Define a compatibility mapping (/fleet:compat <old> <new> <name>)",
    handler: async (args, ctx) => {
      const parts = (args || "").trim().split(/\s+/);
      if (parts.length < 3) {
        ctx.ui.notify("Usage: /fleet:compat <old-contract> <new-contract> <name>", "warning");
        return;
      }
      const res = addCompatMapping(loadState(), {
        oldContract: parts[0], newContract: parts[1], name: parts.slice(2).join(" "),
      });
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
    },
  });

  pi.registerTool({
    name: "fleet_add_migration_phase",
    label: "Add Migration Phase",
    description:
      "Add an ordered migration step. rollbackPlan is mandatory — a step that cannot be undone should be its own explicit decision, not a line in a plan.",
    parameters: Type.Object({
      name: Type.String(),
      rollbackPlan: Type.String({ description: "How to undo this step" }),
      order: Type.Optional(Type.Number({ description: "Defaults to next available" })),
      description: Type.Optional(Type.String()),
      oldComponents: Type.Optional(Type.Array(Type.String())),
      newComponents: Type.Optional(Type.Array(Type.String())),
      compatibilityLayer: Type.Optional(Type.String()),
      validationCriteria: Type.Optional(Type.String()),
      coexistenceDuration: Type.Optional(Type.String()),
      consumerMigrationStrategy: Type.Optional(Type.String()),
      retirementCondition: Type.Optional(Type.String()),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addMigrationPhase(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_add_compat_mapping",
    label: "Add Compatibility Mapping",
    description: "Map an old contract to its replacement so consumers can move without a flag day.",
    parameters: Type.Object({
      name: Type.String(),
      oldContract: Type.String(),
      newContract: Type.String(),
      mappingDescription: Type.Optional(Type.String()),
      bidirectional: Type.Optional(Type.Boolean()),
      verificationStrategy: Type.Optional(Type.String({ description: "How equivalence is proven" })),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addCompatMapping(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_list_migration",
    label: "List Migration Plan",
    description: "List migration phases in order and any compatibility mappings.",
    parameters: Type.Object({}),
    async execute(_id, _params, signal, _onUpdate, _ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const state = loadState();
      const p = phases(state);
      const c = mappings(state);
      const lines = [
        ...p.map((x) => `${x.order}. ${x.id} — ${x.name} [${x.status}] rollback: ${x.rollbackPlan ? "yes" : "NO"}`),
        ...c.map((x) => `${x.id} — ${x.oldContract} → ${x.newContract}`),
      ];
      const text = lines.length === 0
        ? "No migration planned. Optional for greenfield work."
        : lines.join("\n");
      return { content: [{ type: "text", text }], details: { phases: p.length, mappings: c.length } };
    },
  });
}