/**
 * fleet-module :: [MACRO] Phase 4 — Module Boundary Decomposition
 *
 * Splits the system into small independently implementable black-box modules.
 * Each module has one responsibility, documented inputs/outputs, bounded state,
 * and a replacement strategy.
 *
 * Gate: Phase 3 (FORMATS + CONTRACTS) must be complete.
 *
 * /fleet:modules   — define module boundaries
 * /fleet:mod-edit  — update an existing module
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface ModuleDef {
  id: string;
  name: string;
  responsibility: string;
  owns: string[];
  doesNotOwn: string[];
  consumesInterfaces: string[];
  exposesInterfaces: string[];
  dependencies: string[];        // other MOD-IDs this module depends on
  invariants: string[];
  replaceable: boolean;
  implementationOwner: string | null;
  testStrategy: string;
  status: "draft" | "review" | "approved";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const MOD_FILE = "05_MODULE_REGISTRY.md";

function cwd(): string {
  return process.cwd();
}

function archPath(...parts: string[]): string {
  return join(cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) {
    try {
      return JSON.parse(readFileSync(jsonPath, "utf8"));
    } catch {
      return null;
    }
  }
  return null;
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeModuleFile(modules: ModuleDef[]) {
  ensureArchDir();
  if (modules.length === 0) {
    writeFileSync(archPath(MOD_FILE), "# Module Registry\n\n*No modules defined yet.*\n", "utf8");
    return;
  }

  const lines = [
    "# Module Registry",
    "",
    `*Generated by fleet-module · ${new Date().toISOString()}*`,
    "",
    "| ID | Name | Responsibility | Status | Owner | Replaceable |",
    "|---|---|---|---|---|---|",
  ];

  for (const m of modules) {
    lines.push(
      `| ${m.id} | ${m.name} | ${m.responsibility.slice(0, 60)}${m.responsibility.length > 60 ? "..." : ""} | ${m.status} | ${m.implementationOwner || "—"} | ${m.replaceable ? "✅" : "❌"} |`
    );
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  for (const m of modules) {
    lines.push(`## ${m.id} — ${m.name}`);
    lines.push("");
    lines.push(`**Responsibility:** ${m.responsibility}`);
    lines.push(`**Status:** ${m.status}  **Owner:** ${m.implementationOwner || "_unassigned_"}  **Replaceable:** ${m.replaceable ? "✅" : "❌"}`);
    lines.push("");
    lines.push("### Owns");
    for (const o of m.owns) lines.push(`- ${o}`);
    if (m.owns.length === 0) lines.push("_none explicitly_");
    lines.push("");
    lines.push("### Does Not Own");
    for (const o of m.doesNotOwn) lines.push(`- ${o}`);
    if (m.doesNotOwn.length === 0) lines.push("_none explicitly_");
    lines.push("");
    lines.push("### Consumes Interfaces");
    for (const i of m.consumesInterfaces) lines.push(`- ${i}`);
    if (m.consumesInterfaces.length === 0) lines.push("_none_");
    lines.push("");
    lines.push("### Exposes Interfaces");
    for (const i of m.exposesInterfaces) lines.push(`- ${i}`);
    if (m.exposesInterfaces.length === 0) lines.push("_none_");
    lines.push("");
    lines.push("### Module Dependencies");
    for (const d of m.dependencies) lines.push(`- ${d}`);
    if (m.dependencies.length === 0) lines.push("_none_");
    lines.push("");
    lines.push("### Invariants");
    for (const inv of m.invariants) lines.push(`- ${inv}`);
    if (m.invariants.length === 0) lines.push("_none_");
    lines.push("");
    lines.push("### Test Strategy");
    lines.push(m.testStrategy || "_not specified_");
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  writeFileSync(archPath(MOD_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let modules: ModuleDef[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("mod-state.json");
    if (existsSync(statePath)) {
      try {
        const saved = JSON.parse(readFileSync(statePath, "utf8"));
        modules = saved.modules || [];
      } catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state?.job?.objective) {
      ctx.ui.notify("No job initialized. Run /fleet:new-job first.", "warning");
      return false;
    }
    if (!fleet.state.phaseGates?.[3]) {
      ctx.ui.notify("Phase 3 (FORMATS + CONTRACTS) not complete. Run /fleet:format and advance with /fleet:phase 4.", "warning");
      return false;
    }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("mod-state.json"), JSON.stringify({ modules }, null, 2), "utf8");
    writeModuleFile(modules);
  }

  // ─── Command: fleet:modules ────────────────────────────────────────────

  pi.registerCommand("fleet:modules", {
    description: "Define module boundaries (Phase 4)",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "Module decomposition. Each module is a black box with one responsibility, documented interfaces, and bounded state.",
        "info"
      );

      // Show existing contracts for reference
      const fmtPath = archPath("04_FORMAT_REGISTRY.md");
      if (existsSync(fmtPath)) {
        const fmtContent = readFileSync(fmtPath, "utf8");
        const contractLines = fmtContent.split("\n").filter((l) => l.startsWith("| `FMT-"));
        if (contractLines.length > 0) {
          ctx.ui.notify(`Existing contracts:\n${contractLines.join("\n")}`, "info");
        }
      }

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input(
          `Module #${modules.length + 1} name (e.g., 'Document Store', 'Search Engine') — or blank to stop`,
          ""
        );
        if (!name) { addMore = false; break; }

        const responsibility = await ctx.ui.input("Single responsibility (one clear sentence)", "");
        const ownsRaw = await ctx.ui.input("Owns (comma-separated, what data/code belongs here)", "");
        const owns = ownsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const dnoRaw = await ctx.ui.input("Explicitly does NOT own (comma-separated)", "");
        const doesNotOwn = dnoRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const consRaw = await ctx.ui.input("Consumes interfaces (FMT-xxx IDs, comma-separated)", "");
        const consumesInterfaces = consRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const expRaw = await ctx.ui.input("Exposes interfaces (FMT-xxx IDs, comma-separated)", "");
        const exposesInterfaces = expRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const depsRaw = await ctx.ui.input("Module dependencies (MOD-xxx IDs, comma-separated)", "");
        const dependencies = depsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const invRaw = await ctx.ui.input("Invariants (comma-separated)", "");
        const invariants = invRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const testStrategy = await ctx.ui.input("Test strategy", "unit tests + integration via shared contracts");

        const id = `MOD-${String(modules.length + 1).padStart(3, "0")}`;

        const mod: ModuleDef = {
          id,
          name,
          responsibility: responsibility || name,
          owns,
          doesNotOwn,
          consumesInterfaces,
          exposesInterfaces,
          dependencies,
          invariants,
          replaceable: true,
          implementationOwner: null,
          testStrategy: testStrategy || "unit tests",
          status: "draft",
        };

        modules.push(mod);

        // Assign owner
        const assignOwner = await ctx.ui.confirm(
          "Assign implementation owner?",
          "This will be the primary agent responsible"
        );
        if (assignOwner) {
          const owner = await ctx.ui.input("Owner station/agent name (e.g., 'forgecrafter', 'nova')", "");
          if (owner) mod.implementationOwner = owner;
        }

        saveState();
        ctx.ui.notify(`🧩 Module ${id} — "${name}" defined`, "info");

        const more = await ctx.ui.confirm("Add another module?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${modules.length} modules defined in ${MOD_FILE}`, "info");

      // Check for dependency cycle warning
      if (modules.length > 1) {
        ctx.ui.notify(
          "⚠️  Review the module graph for dependency cycles before advancing to Phase 5.",
          "info"
        );
      }
    },
  });

  // ─── Command: fleet:mod-edit ───────────────────────────────────────────

  pi.registerCommand("fleet:mod-edit", {
    description: "Edit an existing module (usage: /fleet:mod-edit <MOD-xxx> <field> <value>)",
    handler: async (args, ctx) => {
      if (!checkGate(ctx)) return;

      const parts = (args || "").trim().split(/\s+/);
      if (parts.length < 3) {
        ctx.ui.notify(
          "Usage: /fleet:mod-edit <MOD-id> <field> <value> | /fleet:mod-edit <MOD-id> (interactive)",
          "warning"
        );
        return;
      }

      const modId = parts[0].toUpperCase();
      const mod = modules.find((m) => m.id === modId);
      if (!mod) {
        ctx.ui.notify(`Module ${modId} not found. Available: ${modules.map((m) => m.id).join(", ")}`, "error");
        return;
      }

      // If user provides field + value inline
      if (parts.length >= 3 && parts[1] !== "interactive") {
        const field = parts[1].toLowerCase();
        const value = parts.slice(2).join(" ");
        switch (field) {
          case "owner":
            mod.implementationOwner = value;
            break;
          case "responsibility":
            mod.responsibility = value;
            break;
          case "status":
            if (["draft", "review", "approved"].includes(value)) {
              mod.status = value as any;
            } else {
              ctx.ui.notify("Status must be: draft, review, or approved", "warning");
              return;
            }
            break;
          case "replaceable":
            mod.replaceable = value === "true" || value === "yes";
            break;
          default:
            ctx.ui.notify(`Unknown field: ${field}. Fields: owner, responsibility, status, replaceable`, "warning");
            return;
        }
        saveState();
        ctx.ui.notify(`✅ ${modId}: ${field} updated`, "info");
        return;
      }

      // Interactive edit
      ctx.ui.notify(`Editing ${modId} — "${mod.name}"`, "info");

      const resp = await ctx.ui.input("Responsibility", mod.responsibility);
      if (resp) mod.responsibility = resp;

      const owner = await ctx.ui.input("Implementation owner", mod.implementationOwner || "");
      mod.implementationOwner = owner || null;

      const statusRaw = await ctx.ui.select("Status", [
        { label: "Draft", value: "draft" },
        { label: "Review", value: "review" },
        { label: "Approved", value: "approved" },
      ]);
      if (statusRaw) mod.status = statusRaw as any;

      saveState();
      ctx.ui.notify(`✅ ${modId} updated`, "info");
    },
  });
}