/**
 * fleet-migration :: [MACRO] Phase 6b — Migration & Compatibility Planning
 *
 * Plans incremental migration from existing systems.
 * Designs compatibility layers, coexistence periods, and progressive
 * consumer migration to avoid hard cutovers.
 *
 * Gate: Phase 5 (DEPENDENCIES + EXTENSIONS) must be complete.
 * Optional: skip for greenfield systems.
 *
 * /fleet:migration   — define a migration plan
 * /fleet:compat      — define compatibility layer
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface MigrationPhase {
  id: string;
  name: string;
  order: number;
  description: string;
  oldComponents: string[];
  newComponents: string[];
  compatibilityLayer: string;
  validationCriteria: string;
  rollbackPlan: string;
  status: "planned" | "in-progress" | "completed";

  // Coexistence
  coexistenceDuration: string;
  consumerMigrationStrategy: string;
  retirementCondition: string;
}

interface CompatibilityMapping {
  id: string;
  name: string;
  oldContract: string;   // format/interface ID
  newContract: string;
  mappingDescription: string;
  bidirectional: boolean;
  verificationStrategy: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const MIG_FILE = "10_MIGRATION_PLAN.md";

function cwd(): string { return process.cwd(); }
function archPath(...parts: string[]): string { return join(cwd(), ARCH_DIR, ...parts); }
function ensureArchDir() { const p = archPath(); if (!existsSync(p)) mkdirSync(p, { recursive: true }); }

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) { try { return JSON.parse(readFileSync(jsonPath, "utf8")); } catch { return null; } }
  return null;
}

function writeMigrationFile(phases: MigrationPhase[], mappings: CompatibilityMapping[]) {
  ensureArchDir();
  const lines = ["# Migration Plan", "", `*Generated by fleet-migration · ${new Date().toISOString()}*`, ""];

  lines.push("## Migration Phases");
  lines.push("");
  for (const p of phases.sort((a, b) => a.order - b.order)) {
    lines.push(`### ${p.id}: ${p.name} (Phase ${p.order})`);
    lines.push(`**Status:** ${p.status}`);
    lines.push("");
    lines.push(p.description);
    lines.push("");
    lines.push(`**Old Components:** ${p.oldComponents.join(", ") || "—"}`);
    lines.push(`**New Components:** ${p.newComponents.join(", ") || "—"}`);
    lines.push(`**Compatibility Layer:** ${p.compatibilityLayer}`);
    lines.push(`**Coexistence Duration:** ${p.coexistenceDuration}`);
    lines.push(`**Consumer Migration:** ${p.consumerMigrationStrategy}`);
    lines.push(`**Retirement Condition:** ${p.retirementCondition || "All consumers migrated"}`);
    lines.push(`**Validation:** ${p.validationCriteria}`);
    lines.push(`**Rollback:** ${p.rollbackPlan}`);
    lines.push("---");
    lines.push("");
  }

  if (mappings.length > 0) {
    lines.push("## Compatibility Mappings");
    lines.push("");
    for (const m of mappings) {
      lines.push(`### ${m.id} — ${m.name}`);
      lines.push(`**Old:** ${m.oldContract}  **→ New:** ${m.newContract}`);
      lines.push(`**Bidirectional:** ${m.bidirectional ? "✅" : "❌"}`);
      lines.push("");
      lines.push(m.mappingDescription);
      lines.push(`**Verification:** ${m.verificationStrategy}`);
      lines.push("---");
      lines.push("");
    }
  }

  if (phases.length === 0) lines.push("*No migration planned (greenfield or not yet defined).*");
  writeFileSync(archPath(MIG_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let phases: MigrationPhase[] = [];
  let mappings: CompatibilityMapping[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("mig-state.json");
    if (existsSync(statePath)) {
      try { const s = JSON.parse(readFileSync(statePath, "utf8")); phases = s.phases || []; mappings = s.mappings || []; }
      catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state?.job?.objective) { ctx.ui.notify("No job initialized.", "warning"); return false; }
    if (!fleet.state.phaseGates?.[5]) { ctx.ui.notify("Phase 5 not complete.", "warning"); return false; }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("mig-state.json"), JSON.stringify({ phases, mappings }, null, 2), "utf8");
    writeMigrationFile(phases, mappings);
  }

  // ─── Command: fleet:migration ──────────────────────────────────────────

  pi.registerCommand("fleet:migration", {
    description: "Define a migration plan (Phase 6b). Optional for greenfield.",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      // Ask if greenfield — skip if so
      const greenfield = await ctx.ui.confirm("Is this a greenfield system?", "Skip migration planning if no existing system to replace.");
      if (greenfield) {
        ctx.ui.notify("Greenfield — no migration plan needed. Skip to Phase 7.", "info");
        return;
      }

      ctx.ui.notify(
        "Migration planning: design incremental bridge from old system to new. Avoid hard cutovers.",
        "info"
      );

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input(`Migration phase #${phases.length + 1} name — or blank to stop`, "");
        if (!name) { addMore = false; break; }

        const order = phases.length + 1;
        const desc = await ctx.ui.input("Description of this phase", "");
        const oldRaw = await ctx.ui.input("Old components (comma-separated)", "");
        const newRaw = await ctx.ui.input("New components (comma-separated)", "");
        const oldComponents = oldRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const newComponents = newRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const compatLayer = await ctx.ui.input("Compatibility layer design", "");
        const coexistence = await ctx.ui.input("Coexistence duration (e.g., '2 weeks', '3 months')", "1 month");
        const consumerMig = await ctx.ui.input("Consumer migration strategy", "Progressive — migrate one consumer at a time");
        const validation = await ctx.ui.input("Validation criteria", "All tests pass on both old and new");
        const rollback = await ctx.ui.input("Rollback plan", "Revert to old system via compatibility layer");
        const retireCondition = await ctx.ui.input("Retirement condition", "All consumers migrated");

        phases.push({
          id: `MIG-${String(phases.length + 1).padStart(3, "0")}`,
          name,
          order,
          description: desc || name,
          oldComponents,
          newComponents,
          compatibilityLayer: compatLayer || "_none_",
          coexistenceDuration: coexistence || "1 month",
          consumerMigrationStrategy: consumerMig || "progressive",
          validationCriteria: validation || "all tests pass",
          rollbackPlan: rollback || "revert to old system",
          retirementCondition: retireCondition || "all consumers migrated",
          status: "planned",
        });
        saveState();
        ctx.ui.notify(`🔄 Migration phase "${name}" defined`, "info");

        const more = await ctx.ui.confirm("Add another phase?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${phases.length} migration phases defined`, "info");
    },
  });

  // ─── Command: fleet:compat ─────────────────────────────────────────────

  pi.registerCommand("fleet:compat", {
    description: "Define a compatibility mapping (usage: /fleet:compat <old> <new> <name>)",
    handler: async (args, ctx) => {
      if (!checkGate(ctx)) return;

      if (args?.trim()) {
        const parts = args.trim().split(/\s+/);
        if (parts.length < 3) {
          ctx.ui.notify("Usage: /fleet:compat <old-contract> <new-contract> <name>", "warning");
          return;
        }
        const mappingDesc = await ctx.ui.input("Mapping description", "");

        mappings.push({
          id: `COMPAT-${String(mappings.length + 1).padStart(3, "0")}`,
          name: parts.slice(2).join(" "),
          oldContract: parts[0],
          newContract: parts[1],
          mappingDescription: mappingDesc || `${parts[0]} → ${parts[1]}`,
          bidirectional: false,
          verificationStrategy: "integration tests",
        });
        saveState();
        ctx.ui.notify(`🔗 Compatibility mapping: ${parts[0]} → ${parts[1]}`, "info");
        return;
      }

      // Interactive
      const name = await ctx.ui.input("Mapping name", "");
      if (!name) { ctx.ui.notify("Cancelled.", "info"); return; }
      const oldC = await ctx.ui.input("Old contract (FMT-xxx)", "");
      const newC = await ctx.ui.input("New contract (FMT-xxx)", "");
      const desc = await ctx.ui.input("Mapping description", "");
      const bidir = await ctx.ui.confirm("Bidirectional?", "");
      const verify = await ctx.ui.input("Verification strategy", "integration tests + compatibility tests");

      mappings.push({
        id: `COMPAT-${String(mappings.length + 1).padStart(3, "0")}`,
        name,
        oldContract: oldC,
        newContract: newC,
        mappingDescription: desc || `${oldC} ↔ ${newC}`,
        bidirectional: bidir,
        verificationStrategy: verify,
      });
      saveState();
      ctx.ui.notify(`🔗 Compatibility mapping "${name}" defined`, "info");
    },
  });
}