/**
 * fleet-module :: Phase 4 — Module Boundaries
 *
 * Each module declares one responsibility, the state it owns, the interfaces it
 * consumes and exposes, and the modules it depends on. The dependency graph is
 * verified acyclic in Phase 7, so every reference recorded here is load-bearing.
 *
 * Commands: /fleet:modules /fleet:mod-edit
 * Tools:    fleet_define_module, fleet_edit_module, fleet_list_modules
 *
 * Usage: pi -e extensions/fleet-module.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import {
  MOD_FILE, archPath, ensureArchDir, loadState, saveState, audit, phaseBrief,
} from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ModuleDef {
  id: string;
  name: string;
  responsibility: string;
  owns: string[];
  doesNotOwn: string[];
  consumesInterfaces: string[];
  exposesInterfaces: string[];
  dependencies: string[];
  invariants: string[];
  replaceable: boolean;
  implementationOwner: string | null;
  testStrategy: string;
  status: "draft" | "review" | "approved";
}

// ─── Operations ──────────────────────────────────────────────────────────────

function modules(state: FleetState): ModuleDef[] {
  if (!state.modules) state.modules = [];
  return state.modules as ModuleDef[];
}

const FIELDS: Record<string, keyof ModuleDef> = {
  responsibility: "responsibility",
  owns: "owns",
  doesnotown: "doesNotOwn",
  consumes: "consumesInterfaces",
  exposes: "exposesInterfaces",
  dependencies: "dependencies",
  invariants: "invariants",
  replaceable: "replaceable",
  owner: "implementationOwner",
  teststrategy: "testStrategy",
  status: "status",
};

export function defineModule(state: FleetState, input: Partial<ModuleDef>) {
  const list = modules(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.responsibility?.trim()) {
    return { ok: false, message: "responsibility is required — a module without one has no boundary" };
  }

  const id = input.id?.trim() || `MOD-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((m) => m.id === id)) return { ok: false, message: `${id} already exists` };

  const mod: ModuleDef = {
    id,
    name: input.name.trim(),
    responsibility: input.responsibility.trim(),
    owns: input.owns || [],
    doesNotOwn: input.doesNotOwn || [],
    consumesInterfaces: input.consumesInterfaces || [],
    exposesInterfaces: input.exposesInterfaces || [],
    dependencies: (input.dependencies || []).filter((d) => d !== id),
    invariants: input.invariants || [],
    replaceable: input.replaceable !== false,
    implementationOwner: input.implementationOwner || null,
    testStrategy: input.testStrategy?.trim() || "",
    status: "draft",
  };

  list.push(mod);
  saveState(state);
  writeModuleFile(state);
  audit(`module defined ${id}`, state);
  return { ok: true, message: `${id} defined (${list.length} total)` };
}

export function editModule(state: FleetState, id: string, field: string, value: string) {
  const mod = modules(state).find((m) => m.id === id);
  if (!mod) return { ok: false, message: `Module ${id} not found` };

  const key = FIELDS[field.toLowerCase().replace(/[\s-]/g, "")];
  if (!key) return { ok: false, message: `Unknown field "${field}". Known: ${Object.keys(FIELDS).join(", ")}` };

  const listFields = ["owns", "doesNotOwn", "consumesInterfaces", "exposesInterfaces", "dependencies", "invariants"];
  if (listFields.includes(key as string)) {
    (mod as any)[key] = value.split(",").map((s) => s.trim()).filter(Boolean);
  } else if (key === "replaceable") {
    mod.replaceable = /^(true|yes|y|true)$/i.test(value);
  } else {
    (mod as any)[key] = value;
  }

  saveState(state);
  writeModuleFile(state);
  audit(`module edited ${id}.${field}`, state);
  return { ok: true, message: `${id}.${key} updated` };
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeModuleFile(state: FleetState) {
  ensureArchDir();
  const list = modules(state);
  if (list.length === 0) {
    writeFileSync(archPath(MOD_FILE), "# Module Registry\n\n*No modules defined yet.*\n", "utf8");
    return;
  }
  const lines = [
    "# Module Registry",
    "",
    `*Generated by fleet-module · ${new Date().toISOString()}*`,
    "",
    "| ID | Name | Responsibility | Status | Owner | Replaceable |",
    "|---|---|---|---|---|---|",
  ];
  for (const m of list) {
    const r = m.responsibility.slice(0, 60);
    lines.push(`| ${m.id} | ${m.name} | ${r}${m.responsibility.length > 60 ? "..." : ""} | ${m.status} | ${m.implementationOwner || "—"} | ${m.replaceable ? "✅" : "❌"} |`);
  }
  lines.push("", "---", "");
  for (const m of list) {
    lines.push(`## ${m.id} — ${m.name}`);
    lines.push("");
    lines.push(`**Responsibility:** ${m.responsibility}`);
    lines.push(`**Status:** ${m.status}  **Owner:** ${m.implementationOwner || "_unassigned_"}  **Replaceable:** ${m.replaceable ? "✅" : "❌"}`);
    lines.push("");
    for (const [heading, values] of [
      ["Owns", m.owns],
      ["Does Not Own", m.doesNotOwn],
      ["Consumes Interfaces", m.consumesInterfaces],
      ["Exposes Interfaces", m.exposesInterfaces],
      ["Module Dependencies", m.dependencies],
      ["Invariants", m.invariants],
    ] as const) {
      lines.push(`### ${heading}`);
      if (values.length) for (const v of values) lines.push(`- ${v}`);
      else lines.push("_none_");
      lines.push("");
    }
    lines.push("### Test Strategy");
    lines.push(m.testStrategy || "_not specified_");
    lines.push("");
    lines.push("---");
    lines.push("");
  }
  writeFileSync(archPath(MOD_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:modules", {
    description: "Define module boundaries (Phase 4)",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Module name (blank to finish)", "");
        if (!name) break;
        const responsibility = await ctx.ui.input("Single responsibility", "");
        const owns = await ctx.ui.input("Owns (comma-separated)", "");
        const consumes = await ctx.ui.input("Consumes interfaces (FMT ids)", "");
        const exposes = await ctx.ui.input("Exposes interfaces (FMT ids)", "");
        const deps = await ctx.ui.input("Module dependencies (MOD ids)", "");
        const strategy = await ctx.ui.input("Test strategy", "");
        const split = (s: string) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);
        const res = defineModule(state, {
          name, responsibility, owns: split(owns),
          consumesInterfaces: split(consumes), exposesInterfaces: split(exposes),
          dependencies: split(deps), testStrategy: strategy,
        });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerCommand("fleet:mod-edit", {
    description: "Edit a module (/fleet:mod-edit <MOD-xxx> <field> <value>)",
    handler: async (args, ctx) => {
      const parts = (args || "").trim().split(/\s+/);
      if (parts.length < 3) {
        ctx.ui.notify("Usage: /fleet:mod-edit <MOD-xxx> <field> <value>", "warning");
        return;
      }
      const res = editModule(loadState(), parts[0], parts[1], parts.slice(2).join(" "));
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
    },
  });

  pi.registerTool({
    name: "fleet_define_module",
    label: "Define Module",
    description:
      "Define a module with one responsibility and bounded state. 'owns' must be non-empty and every consumes/exposes/dependencies entry must be an id that already exists — Phase 7 treats dangling references and dependency cycles as REJECT.",
    parameters: Type.Object({
      name: Type.String(),
      responsibility: Type.String({ description: "The single thing this module is responsible for" }),
      owns: Type.Array(Type.String(), { description: "State/concerns this module owns. Must be non-empty." }),
      doesNotOwn: Type.Optional(Type.Array(Type.String())),
      consumesInterfaces: Type.Optional(Type.Array(Type.String(), { description: "FMT- ids" })),
      exposesInterfaces: Type.Optional(Type.Array(Type.String(), { description: "FMT- ids" })),
      dependencies: Type.Optional(Type.Array(Type.String(), { description: "MOD- ids. Keep this acyclic." })),
      invariants: Type.Optional(Type.Array(Type.String())),
      replaceable: Type.Optional(Type.Boolean({ description: "Default true" })),
      implementationOwner: Type.Optional(Type.String()),
      testStrategy: Type.Optional(Type.String({ description: "How this module is tested" })),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      const res = defineModule(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_edit_module",
    label: "Edit Module",
    description:
      "Amend an existing module. List-valued fields accept comma-separated values. Edits to frozen artifacts are refused by the write gate once contracts are frozen.",
    parameters: Type.Object({
      id: Type.String({ description: "MOD- id" }),
      field: Type.String({
        description:
          "One of: responsibility, owns, doesNotOwn, consumes, exposes, dependencies, invariants, replaceable, owner, testStrategy, status",
      }),
      value: Type.String(),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      const p = params as any;
      const res = editModule(loadState(), p.id, p.field, p.value);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_list_modules",
    label: "List Modules",
    description: "List every defined module with its responsibility, owner, and dependencies.",
    parameters: Type.Object({}),
    async execute(_id, _params, _signal, _onUpdate, _ctx) {
      const list = modules(loadState());
      const text = list.length === 0
        ? "No modules defined."
        : list
            .map((m) => `${m.id} — ${m.name}: ${m.responsibility} [deps: ${m.dependencies.join(", ") || "none"}]`)
            .join("\n");
      return { content: [{ type: "text", text }], details: { count: list.length } };
    },
  });
}