/**
 * fleet-dependency :: Phase 5 — Dependency & Adapter Isolation
 *
 * Prevents external systems from contaminating internal architecture.
 * For every dependency (DB, cloud, framework, vendor API, hardware),
 * ensures isolation via adapter + internal contract.
 *
 * Gate: Phase 4 (MODULE BOUNDARIES) must be complete.
 *
 * /fleet:dependencies  — inventory and isolate external dependencies
 * /fleet:adapters      — define adapter boundaries
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface Dependency {
  id: string;
  name: string;
  category: "database" | "cloud" | "framework" | "library" | "hardware" | "vendor-api" | "transport" | "protocol" | "os";
  version: string;
  usedBy: string[];       // MOD-xxx IDs
  adapterRequired: boolean;
  adapterName: string;
  internalContract: string; // FMT-xxx that shields from this dependency
  riskLevel: "low" | "medium" | "high";
  replaceable: boolean;
  notes: string;
}

interface Adapter {
  id: string;
  name: string;
  externalDependency: string;  // DEP-xxx
  internalInterface: string;   // FMT-xxx
  responsibility: string;
  status: "draft" | "approved";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const DEP_FILE = "07_DEPENDENCY_REGISTER.md";

function cwd(): string {
  return process.cwd();
}

function archPath(...parts: string[]): string {
  return join(cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) {
    try {
      return JSON.parse(readFileSync(jsonPath, "utf8"));
    } catch { return null; }
  }
  return null;
}

// ─── Writers ─────────────────────────────────────────────────────────────────

function writeDependencyFile(deps: Dependency[], adapters: Adapter[]) {
  ensureArchDir();

  const lines = ["# Dependency Register", "", `*Generated by fleet-dependency · ${new Date().toISOString()}*`, ""];

  // Dependencies table
  lines.push("## External Dependencies");
  lines.push("");
  lines.push("| ID | Name | Category | Version | Risk | Replaceable | Adapter |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const d of deps) {
    lines.push(
      `| ${d.id} | ${d.name} | ${d.category} | ${d.version} | ${d.riskLevel} | ${d.replaceable ? "✅" : "❌"} | ${d.adapterName || "—"} |`
    );
  }
  lines.push("");

  for (const d of deps) {
    lines.push(`### ${d.id} — ${d.name}`);
    lines.push(`**Category:** ${d.category}  **Version:** ${d.version}  **Risk:** ${d.riskLevel}`);
    lines.push(`**Replaceable:** ${d.replaceable ? "✅" : "❌"}  **Adapter:** ${d.adapterName || "_direct use_"}`);
    lines.push(`**Used by:** ${d.usedBy.join(", ") || "—"}`);
    if (d.internalContract) lines.push(`**Internal contract:** ${d.internalContract}`);
    if (d.notes) lines.push(`**Notes:** ${d.notes}`);
    lines.push("---");
    lines.push("");
  }

  if (adapters.length > 0) {
    lines.push("## Adapter Boundaries");
    lines.push("");
    lines.push("| ID | Adapter | External Dependency | Internal Interface | Status |");
    lines.push("|---|---|---|---|---|");
    for (const a of adapters) {
      lines.push(`| ${a.id} | ${a.name} | ${a.externalDependency} | ${a.internalInterface} | ${a.status} |`);
    }
    lines.push("");
    for (const a of adapters) {
      lines.push(`### ${a.id} — ${a.name}`);
      lines.push(`**External:** ${a.externalDependency} → **Internal:** ${a.internalInterface}`);
      lines.push(a.responsibility || "");
      lines.push(`**Status:** ${a.status}`);
      lines.push("---");
      lines.push("");
    }
  }

  if (deps.length === 0) lines.push("*No dependencies inventoried yet.*");
  writeFileSync(archPath(DEP_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let deps: Dependency[] = [];
  let adapters: Adapter[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("dep-state.json");
    if (existsSync(statePath)) {
      try {
        const saved = JSON.parse(readFileSync(statePath, "utf8"));
        deps = saved.deps || [];
        adapters = saved.adapters || [];
      } catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state?.job?.objective) {
      ctx.ui.notify("No job initialized. Run /fleet:new-job first.", "warning");
      return false;
    }
    if (!fleet.state.phaseGates?.[4]) {
      ctx.ui.notify("Phase 4 (MODULE BOUNDARIES) not complete. Run /fleet:modules and advance with /fleet:phase 5.", "warning");
      return false;
    }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("dep-state.json"), JSON.stringify({ deps, adapters }, null, 2), "utf8");
    writeDependencyFile(deps, adapters);
  }

  // ─── Command: fleet:dependencies ───────────────────────────────────────

  pi.registerCommand("fleet:dependencies", {
    description: "Inventory and isolate external dependencies (Phase 5)",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "Dependency inventory. List every external dependency (DB, cloud, framework, library, hardware, vendor API, transport, protocol, OS). Each must be isolated behind an adapter.",
        "info"
      );

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input(
          `Dependency #${deps.length + 1} name (e.g., 'PostgreSQL 16', 'AWS S3', 'Docker') — or blank to stop`,
          ""
        );
        if (!name) { addMore = false; break; }

        const catRaw = await ctx.ui.select("Category", [
          { label: "Database", value: "database" },
          { label: "Cloud", value: "cloud" },
          { label: "Framework", value: "framework" },
          { label: "Library", value: "library" },
          { label: "Hardware", value: "hardware" },
          { label: "Vendor API", value: "vendor-api" },
          { label: "Transport", value: "transport" },
          { label: "Protocol", value: "protocol" },
          { label: "Operating System", value: "os" },
        ]);
        const version = await ctx.ui.input("Version", "latest");

        const riskRaw = await ctx.ui.select("Risk level", [
          { label: "Low", value: "low" },
          { label: "Medium", value: "medium" },
          { label: "High", value: "high" },
        ]);

        const usedByRaw = await ctx.ui.input("Used by which modules? (MOD-xxx, comma-separated)", "");
        const usedBy = usedByRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const adapterNeeded = await ctx.ui.confirm("Adapter required?", "Should this be isolated behind an internal contract?");
        const adapterName = adapterNeeded ? await ctx.ui.input("Adapter name", `${name.replace(/\s+/g, "-").toLowerCase()}-adapter`) : "";
        const internalContract = adapterNeeded ? await ctx.ui.input("Internal interface (FMT-xxx)", "") : "";
        const replaceable = await ctx.ui.confirm("Replaceable?", "Can this be swapped for an alternative?");
        const notes = await ctx.ui.input("Notes", "");

        const id = `DEP-${String(deps.length + 1).padStart(3, "0")}`;
        deps.push({
          id,
          name,
          category: (catRaw || "library") as any,
          version: version || "latest",
          usedBy,
          adapterRequired: adapterNeeded,
          adapterName: adapterName || "",
          internalContract: internalContract || "",
          riskLevel: (riskRaw || "medium") as any,
          replaceable,
          notes: notes || "",
        });
        saveState();
        ctx.ui.notify(`🔌 ${id} — "${name}" inventoried (risk: ${riskRaw || "medium"})`, "info");

        const more = await ctx.ui.confirm("Add another dependency?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(
        `✅ ${deps.length} dependencies inventoried. ${deps.filter((d) => d.adapterRequired).length} need adapters.`,
        "info"
      );
    },
  });

  // ─── Command: fleet:adapters ───────────────────────────────────────────

  pi.registerCommand("fleet:adapters", {
    description: "Define adapter boundaries for dependencies",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      const unadapted = deps.filter((d) => d.adapterRequired && !adapters.find((a) => a.externalDependency === d.id));
      if (unadapted.length === 0) {
        ctx.ui.notify("All dependencies that need adapters already have one defined.", "info");
      } else {
        ctx.ui.notify(`Dependencies needing adapters: ${unadapted.map((d) => d.id).join(", ")}`, "info");
      }

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input("Adapter name (e.g., 'PostgreSQL Adapter') — or blank to stop", "");
        if (!name) { addMore = false; break; }

        const depId = await ctx.ui.input("External dependency ID (DEP-xxx)", "");
        const dep = deps.find((d) => d.id === depId);
        if (!dep) {
          ctx.ui.notify(`Dependency ${depId} not found.`, "error");
          continue;
        }

        const intId = await ctx.ui.input("Internal interface contract (FMT-xxx)", dep.internalContract || "");
        const responsibility = await ctx.ui.input("Adapter responsibility", `Isolates ${dep.name} behind internal contract`);

        const id = `ADP-${String(adapters.length + 1).padStart(3, "0")}`;
        adapters.push({
          id,
          name,
          externalDependency: depId,
          internalInterface: intId || dep.internalContract,
          responsibility: responsibility || `Isolates ${dep.name}`,
          status: "draft",
        });
        saveState();
        ctx.ui.notify(`🔧 ${id} — "${name}" created`, "info");

        const more = await ctx.ui.confirm("Add another adapter?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${adapters.length} adapters defined`, "info");
    },
  });
}