/**
 * fleet-extension :: Phase 5b — Extension Points & Host Integration
 *
 * Declares where the system accepts extensions, and which module hosts each one.
 * An extension point without a host and an interface is a wish, not a seam.
 *
 * Commands: /fleet:extensions /fleet:exthosts
 * Tools:    fleet_add_extension_point, fleet_add_host, fleet_list_extensions
 *
 * Usage: pi -e extensions/fleet-extension.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import {
  EXT_FILE, archPath, ensureArchDir, loadState, saveState, audit, phaseBrief,
} from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ExtensionPoint {
  id: string;
  capability: string;
  description: string;
  hostModule: string;
  preferred: "standalone-module" | "host-plugin";
  inputs: string[];
  outputs: string[];
  parameters: string[];
  defaultConfig: string;
  hostRequirements: string[];
  optional: boolean;
  status: "proposed" | "approved" | "implemented";
}

export interface HostIntegration {
  id: string;
  name: string;
  hostModule: string;
  registeredExtensions: string[];
  adapterInterface: string;
  dynamicDiscovery: boolean;
  status: "draft" | "approved";
}

// ─── Operations ──────────────────────────────────────────────────────────────

function points(state: FleetState): ExtensionPoint[] {
  if (!state.extensionPoints) state.extensionPoints = [];
  return state.extensionPoints as ExtensionPoint[];
}

function hosts(state: FleetState): HostIntegration[] {
  if (!state.hostIntegrations) state.hostIntegrations = [];
  return state.hostIntegrations as HostIntegration[];
}

export function addExtensionPoint(state: FleetState, input: Partial<ExtensionPoint>) {
  const list = points(state);
  if (!input.capability?.trim()) return { ok: false, message: "capability is required" };
  if (!input.hostModule?.trim()) return { ok: false, message: "hostModule is required — an extension point without a host cannot be implemented" };

  const id = input.id?.trim() || `EXT-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((e) => e.id === id)) return { ok: false, message: `${id} already exists` };

  const p: ExtensionPoint = {
    id,
    capability: input.capability.trim(),
    description: input.description?.trim() || "",
    hostModule: input.hostModule.trim(),
    preferred: input.preferred === "standalone-module" ? "standalone-module" : "host-plugin",
    inputs: input.inputs || [],
    outputs: input.outputs || [],
    parameters: input.parameters || [],
    defaultConfig: input.defaultConfig?.trim() || "",
    hostRequirements: input.hostRequirements || [],
    optional: input.optional !== false,
    status: "proposed",
  };
  list.push(p);
  saveState(state);
  writeExtensionFile(state);
  audit(`extension point ${id} ${p.capability}`, state);
  return { ok: true, message: `${id} recorded (hosted by ${p.hostModule})` };
}

export function addHost(state: FleetState, input: Partial<HostIntegration>) {
  const list = hosts(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.hostModule?.trim()) return { ok: false, message: "hostModule is required" };
  if (!input.adapterInterface?.trim()) return { ok: false, message: "adapterInterface is required — a host without an interface cannot constrain what it loads" };

  const id = input.id?.trim() || `HST-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((h) => h.id === id)) return { ok: false, message: `${id} already exists` };

  const h: HostIntegration = {
    id,
    name: input.name.trim(),
    hostModule: input.hostModule.trim(),
    registeredExtensions: input.registeredExtensions || [],
    adapterInterface: input.adapterInterface.trim(),
    dynamicDiscovery: input.dynamicDiscovery === true,
    status: "draft",
  };
  list.push(h);
  saveState(state);
  writeExtensionFile(state);
  audit(`host ${id} ${h.name}`, state);
  return { ok: true, message: `${id} hosts ${h.registeredExtensions.length} extension(s)` };
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeExtensionFile(state: FleetState) {
  ensureArchDir();
  const e = points(state);
  const h = hosts(state);
  if (e.length === 0 && h.length === 0) {
    writeFileSync(archPath(EXT_FILE), "# Extension Registry\n\n*No extension points recorded yet.*\n", "utf8");
    return;
  }
  const lines = [
    "# Extension Registry",
    "",
    `*Generated by fleet-extension · ${new Date().toISOString()}*`,
    "",
    "| ID | Capability | Host Module | Preferred | Optional | Status |",
    "|---|---|---|---|---|---|",
  ];
  for (const x of e) {
    lines.push(`| ${x.id} | ${x.capability} | ${x.hostModule} | ${x.preferred} | ${x.optional ? "yes" : "no"} | ${x.status} |`);
  }
  lines.push("", "---", "");
  for (const x of e) {
    lines.push(`## ${x.id} — ${x.capability}`);
    lines.push("");
    lines.push(`**Host Module:** ${x.hostModule}  **Preferred:** ${x.preferred}`);
    lines.push(`**Status:** ${x.status}  **Optional:** ${x.optional ? "yes" : "no"}`);
    lines.push("");
    lines.push(x.description || "_unspecified_");
    lines.push("");
    for (const [heading, values] of [
      ["Inputs", x.inputs], ["Outputs", x.outputs],
      ["Parameters", x.parameters], ["Host Requirements", x.hostRequirements],
    ] as const) {
      lines.push(`### ${heading}`);
      if (values.length) for (const v of values) lines.push(`- ${v}`);
      else lines.push("_none_");
      lines.push("");
    }
    lines.push(`**Default Config:** ${x.defaultConfig || "_none_"}`);
    lines.push("");
    lines.push("---", "");
  }
  if (h.length > 0) {
    lines.push("## Host Integrations", "");
    lines.push("| ID | Name | Host Module | Adapter Interface | Dynamic | Status |", "|---|---|---|---|---|---|");
    for (const x of h) {
      lines.push(`| ${x.id} | ${x.name} | ${x.hostModule} | ${x.adapterInterface} | ${x.dynamicDiscovery ? "yes" : "no"} | ${x.status} |`);
    }
    lines.push("");
    for (const x of h) {
      lines.push(`## ${x.id} — ${x.name}`);
      lines.push("");
      lines.push(`**Host Module:** ${x.hostModule}`);
      lines.push(`**Adapter Interface:** ${x.adapterInterface}`);
      lines.push(`**Dynamic Discovery:** ${x.dynamicDiscovery ? "yes" : "no"}  **Status:** ${x.status}`);
      lines.push("");
      lines.push("### Registered Extensions");
      if (x.registeredExtensions.length) for (const r of x.registeredExtensions) lines.push(`- ${r}`);
      else lines.push("_none_");
      lines.push("");
      lines.push("---", "");
    }
  }
  writeFileSync(archPath(EXT_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:extensions", {
    description: "Define extension/plugin boundaries (Phase 5b)",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const capability = await ctx.ui.input("Capability (blank to finish)", "");
        if (!capability) break;
        const host = await ctx.ui.input("Host module (MOD id)", "");
        const desc = await ctx.ui.input("Description", "");
        const res = addExtensionPoint(state, { capability, hostModule: host, description: desc });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerCommand("fleet:exthosts", {
    description: "Define host integration points for extensions",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Host name (blank to finish)", "");
        if (!name) break;
        const host = await ctx.ui.input("Host module (MOD id)", "");
        const iface = await ctx.ui.input("Adapter interface (FMT id)", "");
        const res = addHost(state, { name, hostModule: host, adapterInterface: iface });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerTool({
    name: "fleet_add_extension_point",
    label: "Add Extension Point",
    description:
      "Declare a seam where the system accepts extensions. hostModule must be an existing MOD- id.",
    parameters: Type.Object({
      capability: Type.String(),
      hostModule: Type.String({ description: "MOD- id that hosts the seam" }),
      description: Type.Optional(Type.String()),
      preferred: Type.Optional(
        Type.Union([Type.Literal("standalone-module"), Type.Literal("host-plugin")])
      ),
      inputs: Type.Optional(Type.Array(Type.String())),
      outputs: Type.Optional(Type.Array(Type.String())),
      parameters: Type.Optional(Type.Array(Type.String())),
      defaultConfig: Type.Optional(Type.String()),
      hostRequirements: Type.Optional(Type.Array(Type.String())),
      optional: Type.Optional(Type.Boolean({ description: "Default true" })),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      const res = addExtensionPoint(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_add_host",
    label: "Add Host Integration",
    description:
      "Declare a host that loads extensions. adapterInterface must be an existing FMT- contract that constrains what the host accepts.",
    parameters: Type.Object({
      name: Type.String(),
      hostModule: Type.String({ description: "MOD- id" }),
      adapterInterface: Type.String({ description: "FMT- id" }),
      registeredExtensions: Type.Optional(Type.Array(Type.String(), { description: "EXT- ids" })),
      dynamicDiscovery: Type.Optional(Type.Boolean()),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, _signal, _onUpdate, ctx) {
      const res = addHost(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_list_extensions",
    label: "List Extension Points",
    description: "List every extension point and host integration.",
    parameters: Type.Object({}),
    async execute(_id, _params, _signal, _onUpdate, _ctx) {
      const state = loadState();
      const e = points(state);
      const h = hosts(state);
      const lines = [
        ...e.map((x) => `${x.id} — ${x.capability} (host ${x.hostModule})`),
        ...h.map((x) => `${x.id} — host ${x.name} → ${x.adapterInterface}`),
      ];
      const text = lines.length === 0 ? "No extension points recorded." : lines.join("\n");
      return { content: [{ type: "text", text }], details: { points: e.length, hosts: h.length } };
    },
  });
}