/**
 * fleet-extension :: [MACRO] Phase 5b — Extension & Plugin Model
 *
 * Determines where variability should live outside the core.
 * Prefers standalone modules with thin host adapters over
 * host-specific plugins where possible.
 *
 * Gate: Phase 4 (MODULE BOUNDARIES) must be complete.
 *
 * /fleet:extensions  — define extension/plugin boundaries
 * /fleet:exthosts    — define host integration points
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface ExtensionPoint {
  id: string;
  capability: string;
  description: string;
  hostModule: string;       // MOD-xxx
  preferred: "standalone-module" | "host-plugin";
  inputs: string[];
  outputs: string[];
  parameters: string[];
  defaultConfig: string;
  hostRequirements: string[];
  optional: boolean;
  status: "proposed" | "approved" | "implemented";
}

interface HostIntegration {
  id: string;
  name: string;
  hostModule: string;
  registeredExtensions: string[];  // EXT-xxx
  adapterInterface: string;       // FMT-xxx
  dynamicDiscovery: boolean;       // can extensions register at runtime?
  status: "draft" | "approved";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const EXT_FILE = "08_EXTENSION_REGISTRY.md";

function cwd(): string {
  return process.cwd();
}

function archPath(...parts: string[]): string {
  return join(cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) {
    try { return JSON.parse(readFileSync(jsonPath, "utf8")); }
    catch { return null; }
  }
  return null;
}

// ─── Writers ─────────────────────────────────────────────────────────────────

function writeExtensionFile(exts: ExtensionPoint[], hosts: HostIntegration[]) {
  ensureArchDir();

  const lines = ["# Extension Registry", "", `*Generated by fleet-extension · ${new Date().toISOString()}*`, ""];

  lines.push("## Extension Points");
  lines.push("");
  lines.push("| ID | Capability | Host Module | Model | Optional | Status |");
  lines.push("|---|---|---|---|---|---|");
  for (const e of exts) {
    const modelLabel = e.preferred === "standalone-module" ? "🧩 Standalone" : "🔌 Host Plugin";
    lines.push(`| ${e.id} | ${e.capability} | ${e.hostModule} | ${modelLabel} | ${e.optional ? "✅" : "❌"} | ${e.status} |`);
  }
  lines.push("");

  for (const e of exts) {
    lines.push(`### ${e.id} — ${e.capability}`);
    lines.push(`**Host Module:** ${e.hostModule}  **Model:** ${e.preferred}  **Status:** ${e.status}`);
    lines.push(`**Optional:** ${e.optional ? "Yes. System works without it." : "Required for core functionality."}`);
    lines.push("");
    if (e.description) { lines.push(e.description); lines.push(""); }
    lines.push("**Inputs:** " + (e.inputs.join(", ") || "—"));
    lines.push("**Outputs:** " + (e.outputs.join(", ") || "—"));
    lines.push("**Parameters:** " + (e.parameters.join(", ") || "—"));
    lines.push("**Host Requirements:** " + (e.hostRequirements.join(", ") || "—"));
    lines.push("---");
    lines.push("");
  }

  if (hosts.length > 0) {
    lines.push("## Host Integration Points");
    lines.push("");
    for (const h of hosts) {
      lines.push(`### ${h.id} — ${h.name}`);
      lines.push(`**Host Module:** ${h.hostModule}`);
      lines.push(`**Adapter Interface:** ${h.adapterInterface || "—"}`);
      lines.push(`**Dynamic Discovery:** ${h.dynamicDiscovery ? "✅ Extensions can register at runtime" : "❌ Static registration"}`);
      lines.push(`**Registered Extensions:** ${h.registeredExtensions.join(", ") || "—"}`);
      lines.push("---");
      lines.push("");
    }
  }

  if (exts.length === 0) lines.push("*No extension points defined yet.*");
  writeFileSync(archPath(EXT_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let exts: ExtensionPoint[] = [];
  let hosts: HostIntegration[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("ext-state.json");
    if (existsSync(statePath)) {
      try {
        const saved = JSON.parse(readFileSync(statePath, "utf8"));
        exts = saved.exts || [];
        hosts = saved.hosts || [];
      } catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state?.job?.objective) {
      ctx.ui.notify("No job initialized.", "warning"); return false;
    }
    if (!fleet.state.phaseGates?.[4]) {
      ctx.ui.notify("Phase 4 (MODULE BOUNDARIES) not complete.", "warning"); return false;
    }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("ext-state.json"), JSON.stringify({ exts, hosts }, null, 2), "utf8");
    writeExtensionFile(exts, hosts);
  }

  // ─── Command: fleet:extensions ────────────────────────────────────────

  pi.registerCommand("fleet:extensions", {
    description: "Define extension/plugin boundaries (Phase 5b)",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "Extension points: where should variability live outside the core? Prefer standalone modules over host plugins.",
        "info"
      );

      let addMore = true;
      while (addMore) {
        const capability = await ctx.ui.input(
          `Extension #${exts.length + 1} capability (e.g., 'Authentication Provider', 'Storage Backend', 'Notification Channel') — or blank to stop`,
          ""
        );
        if (!capability) { addMore = false; break; }

        const desc = await ctx.ui.input("Description", "");
        const hostModule = await ctx.ui.input("Host module (MOD-xxx)", "");

        const modelRaw = await ctx.ui.select("Preferred model", [
          { label: "🧩 Standalone module (thin host adapter)", value: "standalone-module" },
          { label: "🔌 Host-specific plugin", value: "host-plugin" },
        ]);
        const preferred = (modelRaw || "standalone-module") as "standalone-module" | "host-plugin";

        const inputsRaw = await ctx.ui.input("Inputs (comma-separated)", "");
        const inputs = inputsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const outputsRaw = await ctx.ui.input("Outputs (comma-separated)", "");
        const outputs = outputsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const paramsRaw = await ctx.ui.input("Parameters (comma-separated)", "");
        const parameters = paramsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const optional = await ctx.ui.confirm("Optional?", "System works without this extension?");
        const id = `EXT-${String(exts.length + 1).padStart(3, "0")}`;

        exts.push({
          id,
          capability,
          description: desc || "",
          hostModule: hostModule || "—",
          preferred,
          inputs,
          outputs,
          parameters,
          defaultConfig: "",
          hostRequirements: [],
          optional,
          status: "proposed",
        });
        saveState();
        ctx.ui.notify(`🧩 ${id} — "${capability}" registered (${preferred === "standalone-module" ? "standalone" : "plugin"})`, "info");

        // Check for dynamic discovery
        const dynamic = await ctx.ui.confirm("Supports dynamic discovery?", "Can extensions register at runtime without host modification?");
        if (dynamic || hosts.length === 0) {
          const host = hosts.find((h) => h.hostModule === hostModule);
          if (host) {
            host.registeredExtensions.push(id);
          } else {
            hosts.push({
              id: `HOST-${String(hosts.length + 1).padStart(3, "0")}`,
              name: `${hostModule || "unknown"} host`,
              hostModule: hostModule || "—",
              registeredExtensions: [id],
              adapterInterface: "",
              dynamicDiscovery: dynamic,
              status: "draft",
            });
          }
          saveState();
        }

        const more = await ctx.ui.confirm("Add another extension?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${exts.length} extension points defined`, "info");
    },
  });

  // ─── Command: fleet:exthosts ──────────────────────────────────────────

  pi.registerCommand("fleet:exthosts", {
    description: "Define host integration points for extensions",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input("Host name (e.g., 'Core Storage Host') — or blank to stop", "");
        if (!name) { addMore = false; break; }

        const hostModule = await ctx.ui.input("Host module (MOD-xxx)", "");
        const adapterInterface = await ctx.ui.input("Adapter interface (FMT-xxx)", "");

        const dynamic = await ctx.ui.confirm("Dynamic discovery?", "Can extensions register at runtime?");
        const registeredRaw = await ctx.ui.input("Registered extension IDs (EXT-xxx, comma)", "");
        const registered = registeredRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const id = `HOST-${String(hosts.length + 1).padStart(3, "0")}`;
        hosts.push({
          id,
          name,
          hostModule: hostModule || "—",
          registeredExtensions: registered,
          adapterInterface: adapterInterface || "",
          dynamicDiscovery: dynamic,
          status: "draft",
        });
        saveState();
        ctx.ui.notify(`🏠 ${id} — "${name}" registered`, "info");

        const more = await ctx.ui.confirm("Add another host?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${hosts.length} host integration points defined`, "info");
    },
  });
}