/**
 * fleet-tooling :: Phase 6 — Tooling & Simulation Planning
 *
 * Makes every important contract independently observable and testable.
 * For each module/interface, defines the minimal executable harness needed
 * so downstream agents test without the full application.
 *
 * Gate: Phase 5 (DEPENDENCIES + EXTENSIONS) must be complete.
 *
 * /fleet:tooling   — define test harnesses and tooling for modules
 * /fleet:harness   — define a specific test harness
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

type HarnessType =
  | "minimal-test-app"
  | "inspector"
  | "logger"
  | "recorder"
  | "playback"
  | "mock-producer"
  | "mock-consumer"
  | "simulator"
  | "visualizer"
  | "scripting-harness"
  | "compatibility-test";

interface ToolingItem {
  id: string;
  name: string;
  harnessType: HarnessType;
  targetModule: string;   // MOD-xxx or FMT-xxx
  description: string;
  language: string;
  dependencies: string[];
  status: "planned" | "implemented" | "obsolete";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const TOOL_FILE = "09_TOOLING_PLAN.md";

function cwd(): string { return process.cwd(); }
function archPath(...parts: string[]): string { return join(cwd(), ARCH_DIR, ...parts); }
function ensureArchDir() { const p = archPath(); if (!existsSync(p)) mkdirSync(p, { recursive: true }); }

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) { try { return JSON.parse(readFileSync(jsonPath, "utf8")); } catch { return null; } }
  return null;
}

function writeToolingFile(items: ToolingItem[]) {
  ensureArchDir();
  if (items.length === 0) {
    writeFileSync(archPath(TOOL_FILE), "# Tooling Plan\n\n*No tooling planned yet.*\n", "utf8");
    return;
  }
  const lines = ["# Tooling Plan", "", `*Generated by fleet-tooling · ${new Date().toISOString()}*`, ""];
  lines.push("| ID | Name | Type | Target | Status | Language |");
  lines.push("|---|---|---|---|---|---|");
  for (const t of items) {
    lines.push(`| ${t.id} | ${t.name} | ${t.harnessType} | ${t.targetModule} | ${t.status} | ${t.language} |`);
  }
  lines.push("");
  for (const t of items) {
    lines.push(`### ${t.id} — ${t.name}`);
    lines.push(`**Type:** ${t.harnessType}  **Target:** ${t.targetModule}  **Status:** ${t.status}`);
    lines.push(`**Language:** ${t.language}`);
    if (t.dependencies.length) lines.push(`**Dependencies:** ${t.dependencies.join(", ")}`);
    lines.push("");
    lines.push(t.description);
    lines.push("---");
    lines.push("");
  }
  writeFileSync(archPath(TOOL_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let items: ToolingItem[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("tool-state.json");
    if (existsSync(statePath)) {
      try { const s = JSON.parse(readFileSync(statePath, "utf8")); items = s.items || []; }
      catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state?.job?.objective) { ctx.ui.notify("No job initialized.", "warning"); return false; }
    if (!fleet.state.phaseGates?.[5]) { ctx.ui.notify("Phase 5 (DEPENDENCIES + EXTENSIONS) not complete.", "warning"); return false; }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("tool-state.json"), JSON.stringify({ items }, null, 2), "utf8");
    writeToolingFile(items);
  }

  // ─── Command: fleet:tooling ───────────────────────────────────────────

  pi.registerCommand("fleet:tooling", {
    description: "Define test harnesses and tooling (Phase 6)",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "Tooling plan: every important contract needs an independent means of being exercised. Downstream agents should test without the full application.",
        "info"
      );

      const targetModule = await ctx.ui.input("Target module or interface (MOD-xxx or FMT-xxx)", "");
      if (!targetModule) { ctx.ui.notify("Cancelled.", "info"); return; }

      // Show harness types as numbered list
      const types: HarnessType[] = [
        "minimal-test-app", "inspector", "logger", "recorder", "playback",
        "mock-producer", "mock-consumer", "simulator", "visualizer",
        "scripting-harness", "compatibility-test"
      ];
      const typeLabels = types.map((t) => t.replace(/-/g, " "));

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input(`Tooling item name for ${targetModule} — or blank to stop`, "");
        if (!name) { addMore = false; break; }

        const typeIdxRaw = await ctx.ui.select("Harness type", typeLabels.map((l, i) => ({ label: l, value: String(i) })));
        const harnessType = types[parseInt(typeIdxRaw || "0")];

        const description = await ctx.ui.input("Description — what does this harness validate?", "");
        const language = await ctx.ui.input("Implementation language", "python");
        const depsRaw = await ctx.ui.input("Dependencies (comma-separated)", "");
        const dependencies = depsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        items.push({
          id: `TOOL-${String(items.length + 1).padStart(3, "0")}`,
          name,
          harnessType,
          targetModule,
          description: description || name,
          language: language || "python",
          dependencies,
          status: "planned",
        });
        saveState();
        ctx.ui.notify(`🛠️  Added ${harnessType} for ${targetModule}`, "info");

        const more = await ctx.ui.confirm("Add another tooling item for this target?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${items.length} tooling items planned for ${targetModule}`, "info");
    },
  });

  // ─── Command: fleet:harness ────────────────────────────────────────────

  pi.registerCommand("fleet:harness", {
    description: "Quick-add a test harness (usage: /fleet:harness <target> <type> <name>)",
    handler: async (args, ctx) => {
      if (!checkGate(ctx)) return;

      const parts = (args || "").trim().split(/\s+/);
      if (parts.length < 3) {
        ctx.ui.notify("Usage: /fleet:harness <MOD/FMT-xxx> <type> <name>", "warning");
        return;
      }

      const target = parts[0];
      const typeRaw = parts[1].toLowerCase().replace(/-/g, "-");
      const name = parts.slice(2).join(" ");

      const validTypes: HarnessType[] = [
        "minimal-test-app", "inspector", "logger", "recorder", "playback",
        "mock-producer", "mock-consumer", "simulator", "visualizer",
        "scripting-harness", "compatibility-test"
      ];

      let harnessType: HarnessType = "minimal-test-app";
      for (const t of validTypes) {
        if (typeRaw === t || typeRaw === t.replace(/-/g, "")) { harnessType = t; break; }
      }

      items.push({
        id: `TOOL-${String(items.length + 1).padStart(3, "0")}`,
        name,
        harnessType,
        targetModule: target,
        description: `${harnessType} for ${target}`,
        language: "python",
        dependencies: [],
        status: "planned",
      });
      saveState();
      ctx.ui.notify(`🛠️  ${harnessType} "${name}" for ${target}`, "info");
    },
  });
}