/**
 * fleet-primitive :: [MACRO] Phase 2 — Primitive & Domain Model
 *
 * Determines the fundamental information the system operates on.
 * Reads requirements and risk register, then guides primitive identification.
 *
 * Gate: Phase 1 (REQUIREMENTS + RISKS) must be complete.
 *
 * /fleet:primitive       — identify and document the system primitive
 * /fleet:multiplicity    — define multiplicity for key entities
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface PrimitiveCandidate {
  name: string;
  meaning: string;
  operations: string[];
  invariants: string[];
  multiplicity: string;
  advantages: string[];
  limitations: string[];
}

interface PrimitiveState {
  selected: PrimitiveCandidate | null;
  candidates: PrimitiveCandidate[];
  entities: EntityMultiplicity[];
}

interface EntityMultiplicity {
  name: string;
  zeroAllowed: boolean;
  oneAllowed: boolean;
  manyAllowed: boolean;
  nested: boolean;
  shared: boolean;
  notes: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const PRIM_FILE = "03_PRIMITIVE.md";

function cwd(): string {
  return process.cwd();
}

function archPath(...parts: string[]): string {
  return join(cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) {
    try {
      return JSON.parse(readFileSync(jsonPath, "utf8"));
    } catch {
      return null;
    }
  }
  return null;
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writePrimitiveFile(state: PrimitiveState) {
  ensureArchDir();
  const lines = [
    "# Primitive & Domain Model",
    "",
    `*Generated by fleet-primitive · ${new Date().toISOString()}*`,
    "",
  ];

  if (state.selected) {
    const p = state.selected;
    lines.push("## Selected Primitive", "");
    lines.push(`**Name:** ${p.name}`);
    lines.push(`**Meaning:** ${p.meaning}`);
    lines.push("");
    lines.push("### Operations");
    for (const op of p.operations) lines.push(`- ${op}`);
    lines.push("");
    lines.push("### Invariants");
    for (const inv of p.invariants) lines.push(`- ${inv}`);
    lines.push("");
    lines.push(`**Multiplicity:** ${p.multiplicity}`);
    lines.push("");
    lines.push("### Advantages");
    for (const a of p.advantages) lines.push(`- ${a}`);
    lines.push("");
    lines.push("### Limitations");
    for (const l of p.limitations) lines.push(`- ${l}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  if (state.candidates.length > 0) {
    lines.push("## Candidates Considered", "");
    for (const c of state.candidates) {
      if (state.selected && c.name === state.selected.name) continue;
      lines.push(`### ${c.name}`);
      lines.push(c.meaning);
      lines.push("");
      lines.push("**Advantages:**");
      for (const a of c.advantages) lines.push(`- ${a}`);
      lines.push("");
      lines.push("**Limitations:**");
      for (const l of c.limitations) lines.push(`- ${l}`);
      lines.push("---");
      lines.push("");
    }
  }

  if (state.entities.length > 0) {
    lines.push("## Entity Multiplicity", "");
    lines.push("| Entity | Zero | One | Many | Nested | Shared | Notes |");
    lines.push("|---|---|---|---|---|---|---|");
    for (const e of state.entities) {
      lines.push(
        `| ${e.name} | ${e.zeroAllowed ? "✅" : "❌"} | ${e.oneAllowed ? "✅" : "❌"} | ${e.manyAllowed ? "✅" : "❌"} | ${e.nested ? "✅" : "❌"} | ${e.shared ? "✅" : "❌"} | ${e.notes} |`
      );
    }
    lines.push("");
  }

  if (!state.selected && state.candidates.length === 0) {
    lines.push("*No primitive identified yet.*");
    lines.push("");
  }

  writeFileSync(archPath(PRIM_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let primState: PrimitiveState = {
    selected: null,
    candidates: [],
    entities: [],
  };

  // Restore
  pi.on("session_start", async () => {
    const statePath = archPath("prim-state.json");
    if (existsSync(statePath)) {
      try {
        const saved = JSON.parse(readFileSync(statePath, "utf8"));
        primState = saved;
      } catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state || !fleet.state.job?.objective) {
      ctx.ui.notify("No job initialized. Run /fleet:new-job first.", "warning");
      return false;
    }
    if (!fleet.state.phaseGates?.[1]) {
      ctx.ui.notify("Phase 1 (REQUIREMENTS + RISKS) not complete. Run /fleet:requirements and /fleet:risks, then advance with /fleet:phase 2.", "warning");
      return false;
    }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("prim-state.json"), JSON.stringify(primState, null, 2), "utf8");
    writePrimitiveFile(primState);
  }

  // ─── Command: fleet:primitive ──────────────────────────────────────────

  pi.registerCommand("fleet:primitive", {
    description: "Identify the system primitive (Phase 2)",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "Primitive identification. The primitive is the fundamental information the system operates on — the atomic unit of meaning.",
        "info"
      );

      // Read existing requirements for context
      let reqContext = "";
      const reqPath = archPath("01_REQUIREMENTS.md");
      if (existsSync(reqPath)) {
        reqContext = readFileSync(reqPath, "utf8").slice(0, 2000);
      }

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input(
          `Candidate primitive #${primState.candidates.filter((c) => c.name !== primState.selected?.name).length + 1} name (e.g., 'Document', 'Event', 'Entity', 'Message') — or blank to stop`,
          ""
        );
        if (!name) { addMore = false; break; }

        const meaning = await ctx.ui.input(`What does "${name}" represent in the system?`, "");
        const opsRaw = await ctx.ui.input("Operations on this primitive (comma-separated, e.g., 'create, read, update, delete')", "create, read, update, delete");
        const operations = opsRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const invRaw = await ctx.ui.input("Invariants (comma-separated)", "immutable identity");
        const invariants = invRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const multiplicity = await ctx.ui.input("Multiplicity (e.g., 'one-to-many', 'many-to-many', 'singleton')", "many");
        const advRaw = await ctx.ui.input("Advantages (comma-separated)", "");
        const advantages = advRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
        const limRaw = await ctx.ui.input("Limitations (comma-separated)", "");
        const limitations = limRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

        const candidate: PrimitiveCandidate = {
          name,
          meaning: meaning || name,
          operations,
          invariants,
          multiplicity: multiplicity || "many",
          advantages,
          limitations,
        };

        primState.candidates.push(candidate);

        // Ask if this should be the selected primitive
        const select = await ctx.ui.confirm(
          "Select this as the PRIMITIVE?",
          `"${name}" will become the canonical primitive`
        );
        if (select) {
          primState.selected = candidate;
          ctx.ui.notify(`✅ Primitive selected: "${name}"`, "info");
        }

        saveState();
        const more = await ctx.ui.confirm("Add another candidate primitive?", "");
        if (!more) addMore = false;
      }

      if (primState.selected) {
        ctx.ui.notify(`✅ Primitive "${primState.selected.name}" selected and written to ${PRIM_FILE}`, "info");
      } else if (primState.candidates.length > 0) {
        ctx.ui.notify(
          "Candidates recorded but none selected. Use /fleet:decision to escalate if needed.",
          "info"
        );
      }
    },
  });

  // ─── Command: fleet:multiplicity ───────────────────────────────────────

  pi.registerCommand("fleet:multiplicity", {
    description: "Define entity multiplicity (Phase 2) — zero/one/many/nested/shared",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      let addMore = true;
      while (addMore) {
        const name = await ctx.ui.input("Entity name (e.g., 'User', 'Document', 'Project') — or blank to stop", "");
        if (!name) { addMore = false; break; }

        const zero = await ctx.ui.confirm("Zero allowed?", "");
        const one = await ctx.ui.confirm("One allowed?", "");
        const many = await ctx.ui.confirm("Many allowed?", "");
        const nested = await ctx.ui.confirm("Nested allowed?", "");
        const shared = await ctx.ui.confirm("Shared allowed?", "");
        const notes = await ctx.ui.input("Notes", "");

        primState.entities.push({
          name,
          zeroAllowed: zero,
          oneAllowed: one,
          manyAllowed: many,
          nested: nested,
          shared: shared,
          notes: notes || "",
        });

        saveState();
        ctx.ui.notify(`📐 Entity "${name}" multiplicity recorded`, "info");

        const more = await ctx.ui.confirm("Add another entity?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ ${primState.entities.length} entities documented in ${PRIM_FILE}`, "info");
    },
  });
}