/**
 * fleet-format :: [MACRO] Phase 3 — Format & Contract Design
 *
 * Designs the semantic formats through which modules communicate.
 * Treats API, file format, network protocol, event schema, plugin contract,
 * and serialization as related forms of format design.
 *
 * Gate: Phase 2 (PRIMITIVE) must be complete.
 *
 * /fleet:format     — define a semantic format or interface contract
 * /fleet:contracts  — list all registered contracts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface FormatContract {
  id: string;
  name: string;
  type: "interface" | "event" | "file-format" | "protocol" | "serialization" | "plugin";
  semantics: string;
  structure: string;
  invariants: string;
  version: string;

  // Implementation freedom check
  hidesStorage: boolean;
  hidesVendor: boolean;
  hidesPlatform: boolean;
  hidesAlgorithm: boolean;
  alternativeImplementable: boolean;

  consumers: string[];
  producers: string[];
  status: "draft" | "review" | "frozen";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const FMT_FILE = "04_FORMAT_REGISTRY.md";
const INT_FILE = "06_INTERFACE_REGISTRY.md";

function cwd(): string {
  return process.cwd();
}

function archPath(...parts: string[]): string {
  return join(cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) {
    try {
      return JSON.parse(readFileSync(jsonPath, "utf8"));
    } catch {
      return null;
    }
  }
  return null;
}

// ─── Writers ─────────────────────────────────────────────────────────────────

function writeFormatFile(contracts: FormatContract[]) {
  ensureArchDir();
  if (contracts.length === 0) {
    writeFileSync(archPath(FMT_FILE), "# Format Registry\n\n*No formats registered yet.*\n", "utf8");
    return;
  }

  const lines = [
    "# Format Registry",
    "",
    `*Generated by fleet-format · ${new Date().toISOString()}*`,
    "",
    "| ID | Name | Type | Version | Status | Consumers | Producers |",
    "|---|---|---|---|---|---|---|",
  ];

  for (const c of contracts) {
    lines.push(
      `| ${c.id} | ${c.name} | ${c.type} | ${c.version} | ${c.status} | ${c.consumers.join(", ") || "—"} | ${c.producers.join(", ") || "—"} |`
    );
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  for (const c of contracts) {
    lines.push(`## ${c.id} — ${c.name}`);
    lines.push("");
    lines.push("### Semantics");
    lines.push(c.semantics);
    lines.push("");
    lines.push("### Structure");
    lines.push(c.structure);
    lines.push("");
    lines.push("### Invariants");
    lines.push(c.invariants || "_none_");
    lines.push("");
    lines.push("### Implementation Freedom");
    lines.push(`- Storage hidden: ${c.hidesStorage ? "✅" : "❌"}`);
    lines.push(`- Vendor hidden: ${c.hidesVendor ? "✅" : "❌"}`);
    lines.push(`- Platform hidden: ${c.hidesPlatform ? "✅" : "❌"}`);
    lines.push(`- Algorithm hidden: ${c.hidesAlgorithm ? "✅" : "❌"}`);
    lines.push(`- Alternative implementation: ${c.alternativeImplementable ? "✅" : "❌"}`);
    lines.push("");
    lines.push(`**Status:** ${c.status}  **Version:** ${c.version}`);
    lines.push("");
    lines.push(`**Consumers:** ${c.consumers.join(", ") || "—"}`);
    lines.push(`**Producers:** ${c.producers.join(", ") || "—"}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  writeFileSync(archPath(FMT_FILE), lines.join("\n"), "utf8");
}

function writeInterfaceFile(contracts: FormatContract[]) {
  ensureArchDir();
  const interfaces = contracts.filter((c) => c.type === "interface" || c.type === "plugin");

  if (interfaces.length === 0) {
    writeFileSync(archPath(INT_FILE), "# Interface Registry\n\n*No interfaces registered yet.*\n", "utf8");
    return;
  }

  const lines = [
    "# Interface Registry",
    "",
    `*Generated by fleet-format · ${new Date().toISOString()}*`,
    "",
  ];

  for (const c of interfaces) {
    lines.push(`## ${c.id} — ${c.name}`);
    lines.push(`**Type:** ${c.type}`);
    lines.push(`**Status:** ${c.status}  **Version:** ${c.version}`);
    lines.push("");
    lines.push("### Contract");
    lines.push(c.semantics);
    lines.push("");
    lines.push("### Structure");
    lines.push(c.structure);
    lines.push("");
    lines.push("### Invariants");
    lines.push(c.invariants || "_none_");
    lines.push("");
    lines.push("### Implementation Freedom Check");
    lines.push(`- Can another implementation satisfy this contract? ${c.alternativeImplementable ? "✅ Yes" : "❌ No"}`);
    lines.push(`- Storage technology exposed? ${c.hidesStorage ? "✅ No" : "❌ Yes"}`);
    lines.push(`- Vendor concepts exposed? ${c.hidesVendor ? "✅ No" : "❌ Yes"}`);
    lines.push(`- Platform concepts exposed? ${c.hidesPlatform ? "✅ No" : "❌ Yes"}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  writeFileSync(archPath(INT_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let contracts: FormatContract[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("fmt-state.json");
    if (existsSync(statePath)) {
      try {
        const saved = JSON.parse(readFileSync(statePath, "utf8"));
        contracts = saved.contracts || [];
      } catch { /* ignore */ }
    }
  });

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state?.job?.objective) {
      ctx.ui.notify("No job initialized. Run /fleet:new-job first.", "warning");
      return false;
    }
    if (!fleet.state.phaseGates?.[2]) {
      ctx.ui.notify("Phase 2 (PRIMITIVE) not complete. Run /fleet:primitive and advance with /fleet:phase 3.", "warning");
      return false;
    }
    return true;
  }

  function saveState() {
    ensureArchDir();
    writeFileSync(archPath("fmt-state.json"), JSON.stringify({ contracts }, null, 2), "utf8");
    writeFormatFile(contracts);
    writeInterfaceFile(contracts);
  }

  // ─── Command: fleet:format ─────────────────────────────────────────────

  pi.registerCommand("fleet:format", {
    description: "Define a format or interface contract (Phase 3)",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "Define a semantic format. This could be an API interface, file format, event schema, protocol, or serialization.",
        "info"
      );

      const name = await ctx.ui.input("Contract name (e.g., 'Document API', 'Event Bus Protocol')", "");
      if (!name) { ctx.ui.notify("Cancelled.", "info"); return; }

      const typeRaw = await ctx.ui.select("Type", [
        { label: "Interface (API)", value: "interface" },
        { label: "Event Schema", value: "event" },
        { label: "File Format", value: "file-format" },
        { label: "Protocol", value: "protocol" },
        { label: "Serialization", value: "serialization" },
        { label: "Plugin Contract", value: "plugin" },
      ]);
      const type = typeRaw || "interface";

      const semantics = await ctx.ui.input(
        "Semantics — what does this information mean? What guarantees exist?",
        ""
      );
      const structure = await ctx.ui.input(
        "Structure — how is it represented, transferred, parsed?",
        ""
      );
      const invariants = await ctx.ui.input(
        "Invariants — what must always hold true?",
        ""
      );

      // Implementation freedom checks
      ctx.ui.notify("Now checking implementation freedom for this contract.", "info");
      const hideStorage = await ctx.ui.confirm("Storage technology hidden?", "Does the contract expose DB/file specifics?");
      const hideVendor = await ctx.ui.confirm("Vendor concepts hidden?", "Does it mention AWS, Google, etc.?");
      const hidePlatform = await ctx.ui.confirm("Platform concepts hidden?", "Does it require specific OS/hardware?");
      const hideAlgorithm = await ctx.ui.confirm("Internal algorithms hidden?", "Does it expose how things are computed internally?");
      const alternativeImpl = await ctx.ui.confirm("Alternative implementable?", "Could a completely different implementation satisfy this contract?");

      const consumersRaw = await ctx.ui.input("Consumers (comma-separated module names)", "");
      const producersRaw = await ctx.ui.input("Producers (comma-separated module names)", "");
      const consumers = consumersRaw.split(",").map((s: string) => s.trim()).filter(Boolean);
      const producers = producersRaw.split(",").map((s: string) => s.trim()).filter(Boolean);

      const id = `FMT-${String(contracts.length + 1).padStart(3, "0")}`;

      const contract: FormatContract = {
        id,
        name,
        type: type as any,
        semantics: semantics || "_to be defined_",
        structure: structure || "_to be defined_",
        invariants: invariants || "_none_",
        version: "0.1",
        hidesStorage: hideStorage,
        hidesVendor: hideVendor,
        hidesPlatform: hidePlatform,
        hidesAlgorithm: hideAlgorithm,
        alternativeImplementable: alternativeImpl,
        consumers,
        producers,
        status: "draft",
      };

      contracts.push(contract);
      saveState();
      ctx.ui.notify(`📐 Contract ${id} — "${name}" registered (draft)`, "info");

      // Ask to freeze
      const freeze = await ctx.ui.confirm("Freeze this contract?", "Frozen contracts are stable for implementation");
      if (freeze) {
        contract.status = "frozen";
        contract.version = "1.0";
        saveState();

        // Also register in orchestrator state
        const fleet = loadFleetState();
        if (fleet?.state && !fleet.state.frozenContracts.includes(id)) {
          fleet.state.frozenContracts.push(id);
          writeFileSync(archPath("fleet-state.json"), JSON.stringify(fleet, null, 2), "utf8");
        }
        ctx.ui.notify(`❄️ Contract ${id} frozen at v1.0`, "info");
      }
    },
  });

  // ─── Command: fleet:contracts ──────────────────────────────────────────

  pi.registerCommand("fleet:contracts", {
    description: "List all registered contracts and their status",
    handler: async (_args, ctx) => {
      if (contracts.length === 0) {
        ctx.ui.notify("No contracts registered. Use /fleet:format to add one.", "info");
        return;
      }
      const lines = contracts.map(
        (c) => `${c.id}: ${c.name} [${c.type}] v${c.version} — ${c.status}`
      );
      ctx.ui.notify(lines.join("\n"), "info");
    },
  });
}