/**
 * fleet-requirements :: Phase 1 — Requirements & Risk Extraction
 *
 * Reads source material and job definition, then guides the user to extract
 * functional requirements, non-functional requirements, and risks.
 * Writes architecture/01_REQUIREMENTS.md and architecture/02_RISK_REGISTER.md.
 *
 * Gate: Phase 0 (JOB DEFINITION) must be complete.
 *
 * /fleet:requirements — extract functional + non-functional requirements
 * /fleet:risks       — build the risk register
 * /fleet:add-req     — manually add a requirement
 * /fleet:add-risk    — manually add a risk
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface Requirement {
  id: string;
  type: "functional" | "non-functional";
  category: string;
  description: string;
  source: string;
  priority: "critical" | "high" | "medium" | "low";
  status: "proposed" | "approved" | "rejected";
}

interface Risk {
  id: string;
  title: string;
  description: string;
  likelihood: "high" | "medium" | "low";
  impact: "high" | "medium" | "low";
  mitigation: string;
  status: "open" | "mitigated" | "accepted" | "closed";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const REQ_FILE = "01_REQUIREMENTS.md";
const RISK_FILE = "02_RISK_REGISTER.md";

function cwd(): string {
  return process.cwd();
}

function archPath(...parts: string[]): string {
  return join(cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

// ─── Write Requirements ──────────────────────────────────────────────────────

function writeRequirementsFile(
  requirements: Requirement[],
  lifecycle: string,
  teamScale: string
) {
  ensureArchDir();
  const funcReqs = requirements.filter((r) => r.type === "functional");
  const nonFuncReqs = requirements.filter((r) => r.type === "non-functional");

  const lines = [
    "# Requirements",
    "",
    `*Generated by fleet-requirements · ${new Date().toISOString()}*`,
    "",
    "## Expected System Lifetime",
    lifecycle || "_not specified_",
    "",
    "## Expected Team/Fleet Scalability",
    teamScale || "_not specified_",
    "",
    "---",
    "",
  ];

  if (funcReqs.length > 0) {
    lines.push("## Functional Requirements", "");
    for (const r of funcReqs) {
      lines.push(`### ${r.id} [${r.priority}]`);
      lines.push(`**Category:** ${r.category}`);
      lines.push(`**Source:** ${r.source}`);
      lines.push(`**Status:** ${r.status}`);
      lines.push("");
      lines.push(r.description);
      lines.push("");
    }
  }

  if (nonFuncReqs.length > 0) {
    lines.push("## Non-Functional Requirements", "");
    for (const r of nonFuncReqs) {
      lines.push(`### ${r.id} [${r.priority}]`);
      lines.push(`**Category:** ${r.category}`);
      lines.push(`**Source:** ${r.source}`);
      lines.push(`**Status:** ${r.status}`);
      lines.push("");
      lines.push(r.description);
      lines.push("");
    }
  }

  if (requirements.length === 0) {
    lines.push("*No requirements recorded yet.*");
    lines.push("");
  }

  writeFileSync(archPath(REQ_FILE), lines.join("\n"), "utf8");
}

// ─── Write Risk Register ─────────────────────────────────────────────────────

function writeRiskFile(risks: Risk[]) {
  ensureArchDir();
  if (risks.length === 0) {
    writeFileSync(
      archPath(RISK_FILE),
      "# Risk Register\n\n*No risks recorded yet.*\n",
      "utf8"
    );
    return;
  }

  const lines = [
    "# Risk Register",
    "",
    `*Generated by fleet-requirements · ${new Date().toISOString()}*`,
    "",
    "| ID | Title | Likelihood | Impact | Status | Mitigation |",
    "|---|---|---|---|---|---|",
  ];

  for (const r of risks) {
    lines.push(
      `| ${r.id} | ${r.title} | ${r.likelihood} | ${r.impact} | ${r.status} | ${r.mitigation} |`
    );
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  for (const r of risks) {
    lines.push(`## ${r.id} — ${r.title}`);
    lines.push(`**Likelihood:** ${r.likelihood}  **Impact:** ${r.impact}  **Status:** ${r.status}`);
    lines.push("");
    lines.push(r.description);
    lines.push("");
    lines.push(`**Mitigation:** ${r.mitigation}`);
    lines.push("---");
    lines.push("");
  }

  writeFileSync(archPath(RISK_FILE), lines.join("\n"), "utf8");
}

// ─── Load fleet state for gate check ─────────────────────────────────────────

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) {
    try {
      return JSON.parse(readFileSync(jsonPath, "utf8"));
    } catch {
      return null;
    }
  }
  return null;
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let requirements: Requirement[] = [];
  let risks: Risk[] = [];
  let lifecycle = "";
  let teamScale = "";

  // Restore state on session start
  pi.on("session_start", async () => {
    const jsonPath = archPath("fleet-state.json");
    const statePath = archPath("req-state.json");
    if (existsSync(statePath)) {
      try {
        const saved = JSON.parse(readFileSync(statePath, "utf8"));
        requirements = saved.requirements || [];
        risks = saved.risks || [];
        lifecycle = saved.lifecycle || "";
        teamScale = saved.teamScale || "";
      } catch { /* ignore */ }
    }
  });

  // ─── Helper: gate check for Phase 1 ─────────────────────────────────────

  function checkGate(ctx: any): boolean {
    const fleet = loadFleetState();
    if (!fleet || !fleet.state || !fleet.state.job || !fleet.state.job.objective) {
      ctx.ui.notify("No job initialized. Run /fleet:new-job first (Phase 0).", "warning");
      return false;
    }
    if (!fleet.state.phaseGates?.[0]) {
      ctx.ui.notify("Phase 0 (JOB DEFINITION) not complete. Advance to Phase 1 first with /fleet:phase 1.", "warning");
      return false;
    }
    return true;
  }

  // ─── Save state ─────────────────────────────────────────────────────────

  function saveState() {
    ensureArchDir();
    writeFileSync(
      archPath("req-state.json"),
      JSON.stringify({ requirements, risks, lifecycle, teamScale }, null, 2),
      "utf8"
    );
    writeRequirementsFile(requirements, lifecycle, teamScale);
    writeRiskFile(risks);
  }

  // ─── Command: fleet:requirements ────────────────────────────────────────

  pi.registerCommand("fleet:requirements", {
    description: "Extract requirements (Phase 1) — guides through functional + non-functional",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify("Starting requirements extraction. Answer prompts to build the requirements document.", "info");

      // System lifetime
      const life = await ctx.ui.input(
        "Expected system lifetime (e.g., '5 years', '10+ years')",
        lifecycle || "5 years"
      );
      if (life) lifecycle = life;

      // Team/scale expectations
      const scale = await ctx.ui.input(
        "Expected team/fleet scalability (e.g., '3 agents', '10+ agents')",
        teamScale || "3 agents"
      );
      if (scale) teamScale = scale;

      // Functional requirements — loop until user stops
      let addMore = true;
      while (addMore) {
        const desc = await ctx.ui.input(
          `Functional requirement #${requirements.filter((r) => r.type === "functional").length + 1} (or leave blank to stop)`,
          ""
        );
        if (!desc) { addMore = false; break; }

        const cat = await ctx.ui.input("Category (e.g., 'data ingestion', 'search', 'storage')", "general");
        const priorityRaw = await ctx.ui.select("Priority", [
          { label: "Critical", value: "critical" },
          { label: "High", value: "high" },
          { label: "Medium", value: "medium" },
          { label: "Low", value: "low" },
        ]);
        const priority = priorityRaw || "medium";

        requirements.push({
          id: `FR-${String(requirements.filter((r) => r.type === "functional").length + 1).padStart(3, "0")}`,
          type: "functional",
          category: cat || "general",
          description: desc,
          source: "user input",
          priority: priority as any,
          status: "proposed",
        });
        ctx.ui.notify(`📝 Added functional requirement — ${requirements.length} total`, "info");

        const more = await ctx.ui.confirm("Add another functional requirement?", "");
        if (!more) addMore = false;
      }

      // Non-functional requirements
      addMore = true;
      while (addMore) {
        const desc = await ctx.ui.input(
          `Non-functional requirement #${requirements.filter((r) => r.type === "non-functional").length + 1} (or blank to stop)`,
          ""
        );
        if (!desc) { addMore = false; break; }

        const cat = await ctx.ui.input("Category (e.g., 'performance', 'security', 'reliability')", "quality");
        const priorityRaw = await ctx.ui.select("Priority", [
          { label: "Critical", value: "critical" },
          { label: "High", value: "high" },
          { label: "Medium", value: "medium" },
          { label: "Low", value: "low" },
        ]);

        requirements.push({
          id: `NFR-${String(requirements.filter((r) => r.type === "non-functional").length + 1).padStart(3, "0")}`,
          type: "non-functional",
          category: cat || "quality",
          description: desc,
          source: "user input",
          priority: (priorityRaw || "medium") as any,
          status: "proposed",
        });
        ctx.ui.notify(`📝 Added non-functional requirement — ${requirements.length} total`, "info");

        const more = await ctx.ui.confirm("Add another non-functional requirement?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(
        `✅ Requirements written: ${requirements.filter((r) => r.type === "functional").length} functional, ${requirements.filter((r) => r.type === "non-functional").length} non-functional`,
        "info"
      );
    },
  });

  // ─── Command: fleet:risks ──────────────────────────────────────────────

  pi.registerCommand("fleet:risks", {
    description: "Build risk register (Phase 1) — guides through identifying risks",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify("Starting risk identification. Consider: failure points, migration risks, dependency risks, extensibility risks.", "info");

      let addMore = true;
      while (addMore) {
        const title = await ctx.ui.input(
          `Risk #${risks.length + 1} title (or blank to stop)`,
          ""
        );
        if (!title) { addMore = false; break; }

        const desc = await ctx.ui.input("Description", "");
        const likelihoodRaw = await ctx.ui.select("Likelihood", [
          { label: "High", value: "high" },
          { label: "Medium", value: "medium" },
          { label: "Low", value: "low" },
        ]);
        const impactRaw = await ctx.ui.select("Impact", [
          { label: "High", value: "high" },
          { label: "Medium", value: "medium" },
          { label: "Low", value: "low" },
        ]);
        const mitigation = await ctx.ui.input("Mitigation strategy", "");

        risks.push({
          id: `RISK-${String(risks.length + 1).padStart(3, "0")}`,
          title,
          description: desc || title,
          likelihood: (likelihoodRaw || "medium") as any,
          impact: (impactRaw || "medium") as any,
          mitigation: mitigation || "_not specified_",
          status: "open",
        });
        ctx.ui.notify(`⚠️  Added risk: "${title}" — ${risks.length} total`, "info");

        const more = await ctx.ui.confirm("Add another risk?", "");
        if (!more) addMore = false;
      }

      saveState();
      ctx.ui.notify(`✅ Risk register written: ${risks.length} risks identified`, "info");
    },
  });

  // ─── Command: fleet:add-req ────────────────────────────────────────────

  pi.registerCommand("fleet:add-req", {
    description: "Manually add a requirement (usage: /fleet:add-req <type> <description>)",
    handler: async (args, ctx) => {
      if (!checkGate(ctx)) return;
      if (!args?.trim()) {
        ctx.ui.notify("Usage: /fleet:add-req <functional|non-functional> <description>", "warning");
        return;
      }
      const parts = args.trim().split(/\s+/);
      const typeRaw = parts[0].toLowerCase();
      if (typeRaw !== "functional" && typeRaw !== "non-functional") {
        ctx.ui.notify("First argument must be 'functional' or 'non-functional'", "warning");
        return;
      }
      const type = typeRaw as "functional" | "non-functional";
      const desc = parts.slice(1).join(" ");
      if (!desc) {
        ctx.ui.notify("Description required.", "warning");
        return;
      }

      const prefix = type === "functional" ? "FR" : "NFR";
      const count = requirements.filter((r) => r.type === type).length + 1;

      requirements.push({
        id: `${prefix}-${String(count).padStart(3, "0")}`,
        type,
        category: "manual",
        description: desc,
        source: "manual",
        priority: "medium",
        status: "proposed",
      });

      saveState();
      ctx.ui.notify(`📝 Added ${type} requirement: "${desc.slice(0, 60)}..."`, "info");
    },
  });

  // ─── Command: fleet:add-risk ───────────────────────────────────────────

  pi.registerCommand("fleet:add-risk", {
    description: "Manually add a risk (usage: /fleet:add-risk <title> — <description>)",
    handler: async (args, ctx) => {
      if (!checkGate(ctx)) return;
      if (!args?.trim()) {
        ctx.ui.notify("Usage: /fleet:add-risk <title> — <description>", "warning");
        return;
      }
      risks.push({
        id: `RISK-${String(risks.length + 1).padStart(3, "0")}`,
        title: args.trim().split(/ — /)?.[0] || args.trim(),
        description: args.trim().split(/ — /)?.[1] || "",
        likelihood: "medium",
        impact: "medium",
        mitigation: "_pending_",
        status: "open",
      });
      saveState();
      ctx.ui.notify(`⚠️  Added risk: "${risks[risks.length - 1].title}"`, "info");
    },
  });
}