/**
 * fleet-dependency :: Phase 5 — External Dependency Isolation
 *
 * Inventories every external dependency (database, cloud, vendor API, library,
 * transport, OS) and states whether it is shielded behind an internal contract.
 * A dependency that is not shielded is a place where replaceability ends.
 *
 * Commands: /fleet:dependencies /fleet:adapters
 * Tools:    fleet_add_dependency, fleet_add_adapter, fleet_list_dependencies
 *
 * Usage: pi -e extensions/fleet-dependency.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import {
  DEP_FILE, archPath, ensureArchDir, loadState, saveState, audit, phaseBrief, aborted, ABORTED_RESULT } from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface Dependency {
  id: string;
  name: string;
  category: "database" | "cloud" | "framework" | "library" | "hardware" | "vendor-api" | "transport" | "protocol" | "os";
  version: string;
  usedBy: string[];
  adapterRequired: boolean;
  adapterName: string;
  internalContract: string;
  riskLevel: "low" | "medium" | "high";
  replaceable: boolean;
  notes: string;
}

export interface Adapter {
  id: string;
  name: string;
  externalDependency: string;
  internalInterface: string;
  responsibility: string;
  status: "draft" | "approved";
}

const CATEGORIES = ["database", "cloud", "framework", "library", "hardware", "vendor-api", "transport", "protocol", "os"] as const;

// ─── Operations ──────────────────────────────────────────────────────────────

function deps(state: FleetState): Dependency[] {
  if (!state.dependencies) state.dependencies = [];
  return state.dependencies as Dependency[];
}

function adapters(state: FleetState): Adapter[] {
  if (!state.adapters) state.adapters = [];
  return state.adapters as Adapter[];
}

export function addDependency(state: FleetState, input: Partial<Dependency>) {
  const list = deps(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };

  const id = input.id?.trim() || `DEP-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((d) => d.id === id)) return { ok: false, message: `${id} already exists` };

  const dep: Dependency = {
    id,
    name: input.name.trim(),
    category: (CATEGORIES.includes(input.category as any) ? input.category : "library") as Dependency["category"],
    version: input.version?.trim() || "unspecified",
    usedBy: input.usedBy || [],
    adapterRequired: input.adapterRequired !== false,
    adapterName: input.adapterName?.trim() || "",
    internalContract: input.internalContract?.trim() || "",
    riskLevel: (["low", "medium", "high"] as const).includes(input.riskLevel as any)
      ? (input.riskLevel as any)
      : "medium",
    replaceable: input.replaceable !== false,
    notes: input.notes?.trim() || "",
  };

  list.push(dep);
  saveState(state);
  writeDependencyFile(state);
  audit(`dependency ${id} ${dep.name}`, state);
  return { ok: true, message: `${id} recorded (${dep.category}, ${dep.riskLevel} risk)` };
}

export function addAdapter(state: FleetState, input: Partial<Adapter>) {
  const list = adapters(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.internalInterface?.trim()) {
    return { ok: false, message: "internalInterface is required — an adapter without a target interface shields nothing" };
  }

  const id = input.id?.trim() || `ADP-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((a) => a.id === id)) return { ok: false, message: `${id} already exists` };

  const adapter: Adapter = {
    id,
    name: input.name.trim(),
    externalDependency: input.externalDependency?.trim() || "",
    internalInterface: input.internalInterface.trim(),
    responsibility: input.responsibility?.trim() || "",
    status: "draft",
  };
  list.push(adapter);
  saveState(state);
  writeDependencyFile(state);
  audit(`adapter ${id} ${adapter.name}`, state);
  return { ok: true, message: `${id} shields ${adapter.externalDependency || "?"} behind ${adapter.internalInterface}` };
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeDependencyFile(state: FleetState) {
  ensureArchDir();
  const d = deps(state);
  const a = adapters(state);
  if (d.length === 0 && a.length === 0) {
    writeFileSync(archPath(DEP_FILE), "# Dependency Register\n\n*No dependencies recorded yet.*\n", "utf8");
    return;
  }
  const lines = [
    "# Dependency Register",
    "",
    `*Generated by fleet-dependency · ${new Date().toISOString()}*`,
    "",
    "| ID | Name | Category | Version | Risk | Adapter | Contract | Used By |",
    "|---|---|---|---|---|---|---|---|",
  ];
  for (const x of d) {
    lines.push(`| ${x.id} | ${x.name} | ${x.category} | ${x.version} | ${x.riskLevel} | ${x.adapterRequired ? x.adapterName || "❌" : "n/a"} | ${x.internalContract || "—"} | ${x.usedBy.join(", ") || "—"} |`);
  }
  lines.push("", "---", "");
  for (const x of d) {
    lines.push(`## ${x.id} — ${x.name}`);
    lines.push("");
    lines.push(`**Category:** ${x.category}  **Version:** ${x.version}  **Risk:** ${x.riskLevel}`);
    lines.push(`**Adapter Required:** ${x.adapterRequired ? "yes" : "no"}  **Adapter:** ${x.adapterName || "—"}`);
    lines.push("");
    lines.push(`**Internal Contract:** ${x.internalContract || "—"}`);
    lines.push("");
    lines.push("### Used By");
    if (x.usedBy.length) for (const m of x.usedBy) lines.push(`- ${m}`);
    else lines.push("_none_");
    lines.push("");
    lines.push(`**Replaceable:** ${x.replaceable ? "✅" : "❌"}`);
    lines.push("");
    if (x.notes) { lines.push(x.notes); lines.push(""); }
    lines.push("---", "");
  }
  if (a.length > 0) {
    lines.push("## Adapters", "");
    lines.push("| ID | Name | Shields | Internal Interface | Responsibility | Status |", "|---|---|---|---|---|---|");
    for (const x of a) {
      lines.push(`| ${x.id} | ${x.name} | ${x.externalDependency || "—"} | ${x.internalInterface} | ${x.responsibility || "—"} | ${x.status} |`);
    }
    lines.push("");
    for (const x of a) {
      lines.push(`## ${x.id} — ${x.name}`);
      lines.push("");
      lines.push(`**External Dependency:** ${x.externalDependency || "—"}`);
      lines.push(`**Internal Interface:** ${x.internalInterface}`);
      lines.push("");
      lines.push("### Boundary");
      lines.push(x.responsibility || "_unspecified_");
      lines.push("");
      lines.push("---", "");
    }
  }
  writeFileSync(archPath(DEP_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:dependencies", {
    description: "Inventory and isolate external dependencies (Phase 5)",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Dependency name (blank to finish)", "");
        if (!name) break;
        const category = await ctx.ui.input(`Category (${CATEGORIES.join("/")})`, "library");
        const version = await ctx.ui.input("Version", "");
        const usedBy = await ctx.ui.input("Used by (MOD ids, comma-separated)", "");
        const isolate = (await ctx.ui.input("Needs an adapter boundary? (y/n)", "y")) === "y";
        const res = addDependency(state, {
          name, category: category as any, version, isolate,
          adapterRequired: isolate,
          usedBy: usedBy ? usedBy.split(",").map((s) => s.trim()).filter(Boolean) : [],
        } as any);
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerCommand("fleet:adapters", {
    description: "Define adapter boundaries for dependencies",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Adapter name (blank to finish)", "");
        if (!name) break;
        const dep = await ctx.ui.input("Shields which DEP id?", "");
        const iface = await ctx.ui.input("Internal interface (FMT id)", "");
        const resp = await ctx.ui.input("Boundary responsibility", "");
        const res = addAdapter(state, { name, externalDependency: dep, internalInterface: iface, responsibility: resp });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerTool({
    name: "fleet_add_dependency",
    label: "Add Dependency",
    description:
      "Record an external dependency. If adapterRequired is true, Phase 7 verification will REJECT until a matching adapter exists — the adapter is what keeps the dependency replaceable.",
    parameters: Type.Object({
      name: Type.String(),
      category: Type.Optional(Type.Union(CATEGORIES.map((c) => Type.Literal(c) as any))),
      version: Type.Optional(Type.String()),
      usedBy: Type.Optional(Type.Array(Type.String(), { description: "MOD- ids" })),
      adapterRequired: Type.Optional(Type.Boolean({ description: "Default true" })),
      adapterName: Type.Optional(Type.String()),
      internalContract: Type.Optional(Type.String({ description: "FMT- id that shields it" })),
      riskLevel: Type.Optional(Type.Union([Type.Literal("low"), Type.Literal("medium"), Type.Literal("high")])),
      replaceable: Type.Optional(Type.Boolean({ description: "Default true" })),
      notes: Type.Optional(Type.String()),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addDependency(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_add_adapter",
    label: "Add Adapter",
    description:
      "Define the boundary that shields an external dependency. internalInterface must name an existing FMT- contract.",
    parameters: Type.Object({
      name: Type.String(),
      internalInterface: Type.String({ description: "FMT- id this adapter satisfies" }),
      externalDependency: Type.Optional(Type.String({ description: "DEP- id" })),
      responsibility: Type.Optional(Type.String({ description: "What crosses the boundary" })),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addAdapter(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_list_dependencies",
    label: "List Dependencies",
    description: "List every external dependency and whether it is shielded by an adapter.",
    parameters: Type.Object({}),
    async execute(_id, _params, signal, _onUpdate, _ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const state = loadState();
      const list = deps(state);
      const text = list.length === 0
        ? "No dependencies recorded."
        : list
            .map((x) => `${x.id} — ${x.name} (${x.category} ${x.riskLevel}) adapter: ${x.adapterRequired ? x.adapterName || "MISSING" : "n/a"}`)
            .join("\n");
      return { content: [{ type: "text", text }], details: { count: list.length, adapters: adapters(state).length } };
    },
  });
}