/**
 * fleet-format :: Phase 3 — Format + Interface Contracts
 *
 * Defines the contracts that shield the rest of the system from
 * implementation detail. Two documents are rendered from one registry:
 * 04_FORMAT_REGISTRY.md (all contracts) and 06_INTERFACE_REGISTRY.md
 * (interface/plugin contracts only).
 *
 * The two renderings deliberately use different wording for the same
 * implementation-freedom flags — "Storage hidden: ✅" versus
 * "Storage technology exposed? ✅ No". fleet-verify normalizes both forms.
 *
 * Commands: /fleet:format /fleet:contracts
 * Tools:    fleet_define_contract
 *
 * Usage: pi -e extensions/fleet-format.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import {
  FMT_FILE, INT_FILE, archPath, ensureArchDir, loadState, saveState, audit, phaseBrief, aborted, ABORTED_RESULT } from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface FormatContract {
  id: string;
  name: string;
  type: "interface" | "event" | "file-format" | "protocol" | "serialization" | "plugin";
  semantics: string;
  structure: string;
  invariants: string;
  version: string;
  hidesStorage: boolean;
  hidesVendor: boolean;
  hidesPlatform: boolean;
  hidesAlgorithm: boolean;
  alternativeImplementable: boolean;
  consumers: string[];
  producers: string[];
  status: "draft" | "review" | "frozen";
}

// ─── Operations ──────────────────────────────────────────────────────────────

function contracts(state: FleetState): FormatContract[] {
  if (!state.contracts) state.contracts = [];
  return state.contracts as FormatContract[];
}

function nextId(list: FormatContract[]): string {
  return `FMT-${String(list.length + 1).padStart(3, "0")}`;
}

export function defineContract(state: FleetState, input: Partial<FormatContract>) {
  const list = contracts(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.semantics?.trim()) {
    return { ok: false, message: "semantics is required — a contract without meaning cannot be verified" };
  }

  const id = input.id?.trim() || nextId(list);
  const existing = list.find((c) => c.id === id);
  if (existing) {
    if (!input.confirmReplace) {
      return { ok: false, message: `${id} already exists — pass confirmReplace to revise it` };
    }
    Object.assign(existing, buildContract(input, id));
    saveState(state);
    writeFormatFile(state);
    writeInterfaceFile(state);
    audit(`contract revised ${id}`, state);
    return { ok: true, message: `${id} revised` };
  }

  list.push(buildContract(input, id));
  saveState(state);
  writeFormatFile(state);
  writeInterfaceFile(state);
  audit(`contract defined ${id}`, state);
  return { ok: true, message: `${id} defined (${input.type || "interface"})` };
}

function buildContract(input: Partial<FormatContract>, id: string): FormatContract {
  return {
    id,
    name: input.name!.trim(),
    type: (input.type || "interface") as FormatContract["type"],
    semantics: input.semantics!.trim(),
    structure: input.structure?.trim() || "",
    invariants: input.invariants?.trim() || "",
    version: input.version?.trim() || "1",
    hidesStorage: input.hidesStorage !== false,
    hidesVendor: input.hidesVendor !== false,
    hidesPlatform: input.hidesPlatform !== false,
    hidesAlgorithm: input.hidesAlgorithm !== false,
    alternativeImplementable: input.alternativeImplementable !== false,
    consumers: input.consumers || [],
    producers: input.producers || [],
    status: "draft",
  };
}

// ─── Writers ─────────────────────────────────────────────────────────────────

function writeFormatFile(state: FleetState) {
  ensureArchDir();
  const list = contracts(state);
  if (list.length === 0) {
    writeFileSync(archPath(FMT_FILE), "# Format Registry\n\n*No formats registered yet.*\n", "utf8");
    return;
  }
  const lines = [
    "# Format Registry",
    "",
    `*Generated by fleet-format · ${new Date().toISOString()}*`,
    "",
    "| ID | Name | Type | Version | Status | Consumers | Producers |",
    "|---|---|---|---|---|---|---|",
  ];
  for (const c of list) {
    lines.push(
      `| ${c.id} | ${c.name} | ${c.type} | ${c.version} | ${c.status} | ${c.consumers.join(", ") || "—"} | ${c.producers.join(", ") || "—"} |`
    );
  }
  lines.push("", "---", "");
  for (const c of list) {
    lines.push(`## ${c.id} — ${c.name}`);
    lines.push("");
    lines.push("### Semantics");
    lines.push(c.semantics);
    lines.push("");
    lines.push("### Structure");
    lines.push(c.structure || "_unspecified_");
    lines.push("");
    lines.push("### Invariants");
    lines.push(c.invariants || "_none_");
    lines.push("");
    lines.push("### Implementation Freedom");
    lines.push(`- Storage hidden: ${c.hidesStorage ? "✅" : "❌"}`);
    lines.push(`- Vendor hidden: ${c.hidesVendor ? "✅" : "❌"}`);
    lines.push(`- Platform hidden: ${c.hidesPlatform ? "✅" : "❌"}`);
    lines.push(`- Algorithm hidden: ${c.hidesAlgorithm ? "✅" : "❌"}`);
    lines.push(`- Alternative implementation: ${c.alternativeImplementable ? "✅" : "❌"}`);
    lines.push("");
    lines.push(`**Status:** ${c.status}  **Version:** ${c.version}`);
    lines.push("");
    lines.push(`**Consumers:** ${c.consumers.join(", ") || "—"}`);
    lines.push(`**Producers:** ${c.producers.join(", ") || "—"}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }
  writeFileSync(archPath(FMT_FILE), lines.join("\n"), "utf8");
}

function writeInterfaceFile(state: FleetState) {
  ensureArchDir();
  const interfaces = contracts(state).filter((c) => c.type === "interface" || c.type === "plugin");
  if (interfaces.length === 0) {
    writeFileSync(archPath(INT_FILE), "# Interface Registry\n\n*No interfaces registered yet.*\n", "utf8");
    return;
  }
  const lines = ["# Interface Registry", "", `*Generated by fleet-format · ${new Date().toISOString()}*`, ""];
  for (const c of interfaces) {
    lines.push(`## ${c.id} — ${c.name}`);
    lines.push(`**Type:** ${c.type}`);
    lines.push(`**Status:** ${c.status}  **Version:** ${c.version}`);
    lines.push("");
    lines.push("### Contract");
    lines.push(c.semantics);
    lines.push("");
    lines.push("### Structure");
    lines.push(c.structure || "_unspecified_");
    lines.push("");
    lines.push("### Invariants");
    lines.push(c.invariants || "_none_");
    lines.push("");
    lines.push("### Implementation Freedom Check");
    lines.push(`- Can another implementation satisfy this contract? ${c.alternativeImplementable ? "✅ Yes" : "❌ No"}`);
    lines.push(`- Storage technology exposed? ${c.hidesStorage ? "✅ No" : "❌ Yes"}`);
    lines.push(`- Vendor concepts exposed? ${c.hidesVendor ? "✅ No" : "❌ Yes"}`);
    lines.push(`- Platform concepts exposed? ${c.hidesPlatform ? "✅ No" : "❌ Yes"}`);
    lines.push("");
    lines.push(`**Consumers:** ${c.consumers.join(", ") || "—"}`);
    lines.push(`**Producers:** ${c.producers.join(", ") || "—"}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }
  writeFileSync(archPath(INT_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:format", {
    description: "Define a format or interface contract (Phase 3)",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Contract name (blank to finish)", "");
        if (!name) break;
        const type = await ctx.ui.input("Type (interface/event/file-format/protocol/serialization/plugin)", "interface");
        const semantics = await ctx.ui.input("Semantics (what it means)", "");
        const structure = await ctx.ui.input("Structure", "");
        const invariants = await ctx.ui.input("Invariants", "");
        const consumers = await ctx.ui.input("Consumers (MOD ids, comma-separated)", "");
        const producers = await ctx.ui.input("Producers (MOD ids, comma-separated)", "");
        const split = (s: string) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);
        const res = defineContract(state, {
          name, type: type as any, semantics, structure, invariants,
          consumers: split(consumers), producers: split(producers),
        });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
    },
  });

  pi.registerCommand("fleet:contracts", {
    description: "List all registered contracts and their status",
    handler: async (_args, ctx) => {
      const state = loadState();
      const list = contracts(state);
      if (list.length === 0) {
        ctx.ui.notify("No contracts registered.", "info");
        return;
      }
      ctx.ui.notify(
        list
          .map((c) => `${c.id} — ${c.name} [${c.type}] ${c.status} v${c.version}`)
          .join("\n"),
        "info"
      );
    },
  });

  pi.registerTool({
    name: "fleet_define_contract",
    label: "Define Contract",
    description:
      "Define a contract that shields the system from implementation detail. Contracts must state semantics, and must hide at least two of storage/vendor/platform or Phase 7 verification will REJECT them. Reference only MOD- ids that exist — dangling references are also a REJECT.",
    parameters: Type.Object({
      name: Type.String({ description: "Contract name" }),
      semantics: Type.String({ description: "What the contract means — required, and not a placeholder" }),
      type: Type.Optional(
        Type.Union([
          Type.Literal("interface"), Type.Literal("event"), Type.Literal("file-format"),
          Type.Literal("protocol"), Type.Literal("serialization"), Type.Literal("plugin"),
        ])
      ),
      structure: Type.Optional(Type.String({ description: "Shape or schema of the contract" })),
      invariants: Type.Optional(Type.String({ description: "What must always hold" })),
      version: Type.Optional(Type.String()),
      hidesStorage: Type.Optional(Type.Boolean({ description: "Default true" })),
      hidesVendor: Type.Optional(Type.Boolean({ description: "Default true" })),
      hidesPlatform: Type.Optional(Type.Boolean({ description: "Default true" })),
      hidesAlgorithm: Type.Optional(Type.Boolean({ description: "Default true" })),
      alternativeImplementable: Type.Optional(
        Type.Boolean({ description: "Default true. False means only one implementation can satisfy it." })
      ),
      consumers: Type.Optional(Type.Array(Type.String(), { description: "MOD- ids" })),
      producers: Type.Optional(Type.Array(Type.String(), { description: "MOD- ids" })),
      id: Type.Optional(Type.String({ description: "Defaults to the next FMT-nnn" })),
      confirmReplace: Type.Optional(
        Type.Boolean({ description: "Set true to revise an existing contract id" })
      ),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = defineContract(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_list_contracts",
    label: "List Contracts",
    description: "List every registered contract with its type, status, and version.",
    parameters: Type.Object({}),
    async execute(_id, _params, signal, _onUpdate, _ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const list = contracts(loadState());
      const text = list.length === 0
        ? "No contracts registered."
        : list.map((c) => `${c.id} — ${c.name} [${c.type}] ${c.status} v${c.version}`).join("\n");
      return { content: [{ type: "text", text }], details: { count: list.length } };
    },
  });
}