/**
 * fleet-verify :: Phase 7 — Architecture Attack Review
 *
 * The verification agent attempts to break the proposed architecture.
 * Tests: replaceability, independent development, external isolation,
 * minimal format, multiplicity, implementation freedom.
 *
 * This agent should NOT be the same agent that produced the architecture.
 * It uses read-only access — never writes code or artifacts.
 *
 * Gate: Phase 6 (TOOLING + MIGRATION) must be complete.
 *
 * /fleet:verify           — run full attack review on current architecture
 * /fleet:verify-mod <id>  — verify a specific module's contract
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

interface VerificationResult {
  id: string;
  target: string;
  targetType: "primitive" | "interface" | "module" | "dependency" | "migration" | "overall";

  tests: {
    name: string;
    passed: boolean;
    detail: string;
    severity: "low" | "medium" | "high";
  }[];

  summary: "PASS" | "PASS_WITH_CORRECTIONS" | "BLOCKED_BY_DECISION" | "REJECT";
  findings: string[];
  rejectedAssumptions: string[];
  requiredCorrections: string[];
}

// ─── Constants ───────────────────────────────────────────────────────────────

const ARCH_DIR = "architecture";
const VER_FILE = "11_VERIFICATION_PLAN.md";

function archPath(...parts: string[]): string {
  const { join } = require("node:path");
  return join(process.cwd(), ARCH_DIR, ...parts);
}

function ensureArchDir() {
  const { mkdirSync } = require("node:fs");
  const p = archPath();
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadFleetState(): { state: any } | null {
  const jsonPath = archPath("fleet-state.json");
  if (existsSync(jsonPath)) { try { return JSON.parse(readFileSync(jsonPath, "utf8")); } catch { return null; } }
  return null;
}

function checkGate(ctx: any): boolean {
  const fleet = loadFleetState();
  if (!fleet || !fleet.state?.job?.objective) { ctx.ui.notify("No job initialized.", "warning"); return false; }
  if (!fleet.state.phaseGates?.[6]) { ctx.ui.notify("Phase 6 (TOOLING + MIGRATION) not complete. Run /fleet:tooling then /fleet:phase 7.", "warning"); return false; }
  return true;
}

// ─── Write results ────────────────────────────────────────────────────────────

function writeVerificationFile(results: VerificationResult[]) {
  ensureArchDir();
  const lines = ["# Verification Plan & Results", "", `*Generated by fleet-verify · ${new Date().toISOString()}*`, ""];

  // Summary table
  lines.push("## Attack Review Summary");
  lines.push("");
  lines.push("| Target | Type | Verdict |");
  lines.push("|---|---|---|");
  for (const r of results) {
    const verdict = r.summary === "PASS" ? "✅ PASS" : r.summary === "PASS_WITH_CORRECTIONS" ? "⚠️ PASS WITH CORRECTIONS" : r.summary === "BLOCKED_BY_DECISION" ? "🔒 BLOCKED" : "❌ REJECT";
    lines.push(`| ${r.target} | ${r.targetType} | ${verdict} |`);
  }
  lines.push("");

  // Detailed results
  for (const r of results) {
    lines.push(`## ${r.id}: ${r.target}`);
    lines.push(`**Type:** ${r.targetType}  **Verdict:** ${r.summary}`);
    lines.push("");

    lines.push("### Tests");
    for (const t of r.tests) {
      const icon = t.passed ? "✅" : "❌";
      lines.push(`- ${icon} **${t.name}** (${t.severity}): ${t.detail}`);
    }
    lines.push("");

    if (r.findings.length > 0) {
      lines.push("### Findings");
      for (const f of r.findings) lines.push(`- ${f}`);
      lines.push("");
    }
    if (r.rejectedAssumptions.length > 0) {
      lines.push("### Rejected Assumptions");
      for (const a of r.rejectedAssumptions) lines.push(`- ${a}`);
      lines.push("");
    }
    if (r.requiredCorrections.length > 0) {
      lines.push("### Required Corrections");
      for (const c of r.requiredCorrections) lines.push(`- ${c}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  writeFileSync(archPath(VER_FILE), lines.join("\n"), "utf8");
}

// ─── Test runners ─────────────────────────────────────────────────────────────

function runTestsForInterface(
  name: string,
  content: string,
  id: string
): VerificationResult {
  const tests: VerificationResult["tests"] = [];

  // Replaceability test
  const hasAltImpl = content.includes("Alternative implementation");
  tests.push({
    name: "Replaceability",
    passed: hasAltImpl,
    detail: hasAltImpl
      ? "Alternative implementation check present"
      : "No alternative implementation consideration found — marking as finding",
    severity: "high",
  });

  // Implementation freedom tests
  const hidesStorage = content.includes("Storage hidden: ✅") || content.includes("hidesStorage");
  const hidesVendor = content.includes("Vendor hidden: ✅") || content.includes("hidesVendor");
  const hidesPlatform = content.includes("Platform hidden: ✅") || content.includes("hidesPlatform");

  tests.push({
    name: "Storage Hidden",
    passed: hidesStorage,
    detail: hidesStorage ? "Storage technology is not exposed" : "Storage technology may leak through",
    severity: "high",
  });
  tests.push({
    name: "Vendor Hidden",
    passed: hidesVendor,
    detail: hidesVendor ? "Vendor concepts not exposed" : "Vendor concepts may leak through",
    severity: "high",
  });
  tests.push({
    name: "Platform Hidden",
    passed: hidesPlatform,
    detail: hidesPlatform ? "Platform not exposed" : "Platform specifics may leak",
    severity: "medium",
  });

  // Minimal format — heuristic: check description length
  tests.push({
    name: "Semantic Meaning Clear",
    passed: content.length > 100 && content.includes("Semantic"),
    detail: content.length > 100 ? "Semantics section found" : "Very short or no semantics section",
    severity: "medium",
  });

  return {
    id: `VRFY-${id}`,
    target: name,
    targetType: "interface",
    tests,
    summary: tests.every((t) => t.passed) ? "PASS" : "PASS_WITH_CORRECTIONS",
    findings: tests.filter((t) => !t.passed).map((t) => t.detail),
    rejectedAssumptions: [],
    requiredCorrections: tests.filter((t) => !t.passed && t.severity === "high").map((t) => `Fix: ${t.detail}`),
  };
}

function runTestsForModule(
  name: string,
  content: string,
  id: string
): VerificationResult {
  const tests: VerificationResult["tests"] = [];
  const lower = content.toLowerCase();

  // One responsibility
  const hasSingleResp = (content.match(/responsibility/gi) || []).length <= 3;
  tests.push({
    name: "Single Responsibility",
    passed: hasSingleResp,
    detail: hasSingleResp ? "Focused responsibility" : "Multiple responsibility statements — may be too broad",
    severity: "high",
  });

  // Inputs/outputs documented
  const hasConsumes = content.includes("Consumes");
  const hasExposes = content.includes("Exposes");
  tests.push({
    name: "Interfaces Documented",
    passed: hasConsumes && hasExposes,
    detail: hasConsumes && hasExposes ? "Consumes and exposes documented" : "Missing interface documentation",
    severity: "high",
  });

  // Replaceable
  const isReplaceable = content.includes("replaceable: true") || content.includes("✅") && content.includes("Replaceable");
  tests.push({
    name: "Replaceable",
    passed: isReplaceable,
    detail: isReplaceable ? "Module is replaceable" : "Module may not be replaceable — check",
    severity: "high",
  });

  // State ownership clear
  const hasOwns = content.includes("Owns") || content.includes("owns");
  tests.push({
    name: "Bounded State Ownership",
    passed: hasOwns,
    detail: hasOwns ? "State ownership documented" : "No state ownership boundary found",
    severity: "medium",
  });

  return {
    id: `VRFY-MOD-${id}`,
    target: name,
    targetType: "module",
    tests,
    summary: tests.every((t) => t.passed) ? "PASS" : "PASS_WITH_CORRECTIONS",
    findings: tests.filter((t) => !t.passed).map((t) => t.detail),
    rejectedAssumptions: [],
    requiredCorrections: tests.filter((t) => !t.passed && t.severity === "high").map((t) => `Fix: ${t.detail}`),
  };
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  let results: VerificationResult[] = [];

  pi.on("session_start", async () => {
    const statePath = archPath("ver-state.json");
    if (existsSync(statePath)) {
      try { const s = JSON.parse(readFileSync(statePath, "utf8")); results = s.results || []; }
      catch { /* ignore */ }
    }
  });

  function saveState() {
    ensureArchDir();
    const { writeFileSync } = require("node:fs");
    writeFileSync(archPath("ver-state.json"), JSON.stringify({ results }, null, 2), "utf8");
    writeVerificationFile(results);
  }

  // ─── Command: fleet:verify ─────────────────────────────────────────────

  pi.registerCommand("fleet:verify", {
    description: "Run full architecture attack review (Phase 7). Tests all published artifacts.",
    handler: async (_args, ctx) => {
      if (!checkGate(ctx)) return;

      ctx.ui.notify(
        "🔍 Architecture Attack Review — attempting to break the proposed architecture. Tests: replaceability, independence, isolation, minimal format, multiplicity, implementation freedom.",
        "info"
      );

      results = [];

      // Read and verify each artifact
      const artifacts: { file: string; type: VerificationResult["targetType"] }[] = [
        { file: "03_PRIMITIVE.md", type: "primitive" },
        { file: "04_FORMAT_REGISTRY.md", type: "interface" },
        { file: "05_MODULE_REGISTRY.md", type: "module" },
        { file: "06_INTERFACE_REGISTRY.md", type: "interface" },
        { file: "07_DEPENDENCY_REGISTER.md", type: "dependency" },
        { file: "10_MIGRATION_PLAN.md", type: "migration" },
      ];

      for (const { file, type } of artifacts) {
        const path = archPath(file);
        if (!existsSync(path)) {
          ctx.ui.notify(`⏭️  ${file} not found — skipping`, "info");
          continue;
        }

        const content = readFileSync(path, "utf8");
        const name = file.replace(".md", "");

        if (type === "interface" || type === "primitive") {
          results.push(runTestsForInterface(name, content, name));
        } else if (type === "module") {
          results.push(runTestsForModule(name, content, name));
        } else {
          // Basic existence + content check for dependency/migration
          const lines = content.split("\n").filter((l) => l.trim()).length;
          const passed = lines > 5;
          results.push({
            id: `VRFY-${name}`,
            target: name,
            targetType: type,
            tests: [{
              name: "Documented",
              passed,
              detail: passed ? `${lines} lines — adequately documented` : "Very short or empty",
              severity: "high",
            }],
            summary: passed ? "PASS" : "PASS_WITH_CORRECTIONS",
            findings: passed ? [] : ["Document is too short to be meaningful"],
            rejectedAssumptions: [],
            requiredCorrections: passed ? [] : ["Expand documentation"],
          });
        }
      }

      // Overall summary
      const passCount = results.filter((r) => r.summary === "PASS").length;
      const correctCount = results.filter((r) => r.summary === "PASS_WITH_CORRECTIONS").length;
      const blockedCount = results.filter((r) => r.summary === "BLOCKED_BY_DECISION").length;
      const rejectCount = results.filter((r) => r.summary === "REJECT").length;

      // Add overall result
      const overallTests: VerificationResult["tests"] = [];
      if (results.length > 0) {
        overallTests.push({
          name: "All Artifcts Present",
          passed: results.length >= 3,
          detail: `${results.length} out of 6 expected artifacts verified`,
          severity: "high",
        });
        overallTests.push({
          name: "No Rejections",
          passed: rejectCount === 0,
          detail: rejectCount > 0 ? `${rejectCount} artifacts rejected` : "No rejections",
          severity: "high",
        });
      }

      results.push({
        id: "VRFY-OVERALL",
        target: "Full Architecture",
        targetType: "overall",
        tests: overallTests,
        summary: rejectCount > 0 ? "REJECT" : blockedCount > 0 ? "BLOCKED_BY_DECISION" : correctCount > 0 ? "PASS_WITH_CORRECTIONS" : "PASS",
        findings: results.flatMap((r) => r.findings),
        rejectedAssumptions: results.flatMap((r) => r.rejectedAssumptions),
        requiredCorrections: results.flatMap((r) => r.requiredCorrections),
      });

      saveState();

      ctx.ui.notify(
        `✅ Attack review complete: ${passCount} PASS, ${correctCount} PASS_WITH_CORRECTIONS, ${blockedCount} BLOCKED, ${rejectCount} REJECT\nWritten to ${VER_FILE}`,
        "info"
      );
    },
  });

  // ─── Command: fleet:verify-mod ──────────────────────────────────────────

  pi.registerCommand("fleet:verify-mod", {
    description: "Verify a specific module (usage: /fleet:verify-mod <MOD-xxx>)",
    handler: async (args, ctx) => {
      if (!checkGate(ctx)) return;
      if (!args?.trim()) {
        ctx.ui.notify("Usage: /fleet:verify-mod <MOD-xxx>", "warning");
        return;
      }

      const modId = args.trim().toUpperCase();
      const modPath = archPath("05_MODULE_REGISTRY.md");
      if (!existsSync(modPath)) {
        ctx.ui.notify("Module registry not found. Run /fleet:modules first.", "warning");
        return;
      }

      const content = readFileSync(modPath, "utf8");
      // Find the section for this module
      const sections = content.split(/## /);
      const section = sections.find((s) => s.includes(modId));

      if (!section) {
        ctx.ui.notify(`Module ${modId} not found in registry.`, "error");
        return;
      }

      const result = runTestsForModule(modId, section, modId);
      results.push(result);
      saveState();

      ctx.ui.notify(
        `🔍 ${modId}: ${result.summary}\n${result.tests.map((t) => `${t.passed ? "✅" : "❌"} ${t.name}: ${t.detail}`).join("\n")}`,
        "info"
      );
    },
  });
}