/**
 * fleet-requirements :: Phase 1 — Requirements + Risk Register
 *
 * Records functional and non-functional requirements and the risk register.
 * State lives in the canonical fleet store (fleet-core), so it survives session
 * restarts and compaction alongside every other phase.
 *
 * Commands: /fleet:requirements /fleet:risks /fleet:add-req /fleet:add-risk
 * Tools:    fleet_add_requirement, fleet_add_risk, fleet_status_requirements
 *
 * Usage: pi -e extensions/fleet-requirements.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import {
  PHASES, REQ_FILE, RISK_FILE,
  archPath, ensureArchDir, loadState, saveState, audit,
  gateForPhase, phaseBrief, aborted, ABORTED_RESULT } from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface Requirement {
  id: string;
  type: "functional" | "non-functional";
  category: string;
  description: string;
  source: string;
  priority: "critical" | "high" | "medium" | "low";
  status: "proposed" | "approved" | "rejected";
}

export interface Risk {
  id: string;
  title: string;
  description: string;
  likelihood: "high" | "medium" | "low";
  impact: "high" | "medium" | "low";
  mitigation: string;
  status: "open" | "mitigated" | "accepted" | "closed";
}

interface Lifecycle {
  nfrCount: number;
  teamSize: number;
}

// ─── Operations ──────────────────────────────────────────────────────────────

function nextId(prefix: string, existing: any[]): string {
  const n = existing.filter((x) => String(x.id || "").startsWith(prefix)).length + 1;
  return `${prefix}-${String(n).padStart(3, "0")}`;
}

export function addRequirement(
  state: FleetState,
  input: Partial<Requirement>
): { ok: boolean; message: string; requirement?: Requirement } {
  const list = state.requirements || (state.requirements = []);
  if (!input.description?.trim()) return { ok: false, message: "description is required" };

  const type = input.type === "non-functional" ? "non-functional" : "functional";
  const req: Requirement = {
    id: input.id?.trim() || nextId(type === "functional" ? "REQ" : "NFR", list),
    type,
    category: input.category?.trim() || "general",
    description: input.description.trim(),
    source: input.source?.trim() || "unspecified",
    priority: (["critical", "high", "medium", "low"] as const).includes(input.priority as any)
      ? (input.priority as any)
      : "medium",
    status: "proposed",
  };

  if (list.some((r) => r.id === req.id)) {
    return { ok: false, message: `${req.id} already exists` };
  }
  list.push(req);
  saveState(state);
  writeRequirementsFile(state);
  audit(`requirement added ${req.id}`, state);
  return { ok: true, message: `${req.id} recorded (${req.priority})`, requirement: req };
}

export function addRisk(state: FleetState, input: Partial<Risk>): { ok: boolean; message: string; risk?: Risk } {
  const list = state.risks || (state.risks = []);
  if (!input.title?.trim()) return { ok: false, message: "title is required" };

  const risk: Risk = {
    id: input.id?.trim() || nextId("RSK", list),
    title: input.title.trim(),
    description: input.description?.trim() || "",
    likelihood: (["high", "medium", "low"] as const).includes(input.likelihood as any)
      ? (input.likelihood as any)
      : "medium",
    impact: (["high", "medium", "low"] as const).includes(input.impact as any) ? (input.impact as any) : "medium",
    mitigation: input.mitigation?.trim() || "",
    status: "open",
  };

  if (list.some((r) => r.id === risk.id)) return { ok: false, message: `${risk.id} already exists` };
  list.push(risk);
  saveState(state);
  writeRiskFile(state);
  audit(`risk added ${risk.id}`, state);
  return { ok: true, message: `${risk.id} recorded (${risk.likelihood}/${risk.impact})`, risk };
}

// ─── Writers ─────────────────────────────────────────────────────────────────

function writeRequirementsFile(state: FleetState) {
  ensureArchDir();
  const reqs = state.requirements || [];
  if (reqs.length === 0) {
    writeFileSync(archPath(REQ_FILE), "# Requirements\n\n*No requirements recorded yet.*\n", "utf8");
    return;
  }
  const life = state.lifecycle || { nfrCount: reqs.filter((r) => r.type === "non-functional").length, teamSize: 0 };
  const lines = [
    "# Requirements",
    "",
    `*Generated by fleet-requirements · ${new Date().toISOString()}*`,
    "",
    `Functional: ${reqs.filter((r) => r.type === "functional").length} · Non-functional: ${life.nfrCount} · Team size: ${life.teamSize || "unset"}`,
    "",
    "| ID | Type | Category | Priority | Status | Description |",
    "|---|---|---|---|---|---|",
  ];
  for (const r of reqs) {
    lines.push(`| ${r.id} | ${r.type} | ${r.category} | ${r.priority} | ${r.status} | ${r.description.slice(0, 80)} |`);
  }
  lines.push("", "---", "");
  for (const r of reqs) {
    lines.push(`## ${r.id} — ${r.description}`, "");
    lines.push(`**Type:** ${r.type}  **Priority:** ${r.priority}  **Status:** ${r.status}`);
    lines.push(`**Category:** ${r.category}  **Source:** ${r.source}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }
  writeFileSync(archPath(REQ_FILE), lines.join("\n"), "utf8");
}

function writeRiskFile(state: FleetState) {
  ensureArchDir();
  const risks = state.risks || [];
  if (risks.length === 0) {
    writeFileSync(archPath(RISK_FILE), "# Risk Register\n\n*No risks recorded yet.*\n", "utf8");
    return;
  }
  const lines = [
    "# Risk Register",
    "",
    `*Generated by fleet-requirements · ${new Date().toISOString()}*`,
    "",
    "| ID | Title | Likelihood | Impact | Status | Mitigation |",
    "|---|---|---|---|---|---|",
  ];
  for (const r of risks) {
    lines.push(`| ${r.id} | ${r.title} | ${r.likelihood} | ${r.impact} | ${r.status} | ${r.mitigation.slice(0, 60)} |`);
  }
  lines.push("", "---", "");
  for (const r of risks) {
    lines.push(`## ${r.id} — ${r.title}`, "");
    lines.push(`**Likelihood:** ${r.likelihood}  **Impact:** ${r.impact}  **Status:** ${r.status}`);
    lines.push("");
    lines.push(r.description);
    lines.push("");
    lines.push(`**Mitigation:** ${r.mitigation || "_none recorded_"}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }
  writeFileSync(archPath(RISK_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:requirements", {
    description: "Extract requirements (Phase 1)",
    handler: async (args, ctx) => {
      const state = loadState();
      if (!state.job.objective) {
        ctx.ui.notify("No job. Run /fleet:new-job first.", "warning");
        return;
      }
      const blocked = gateForPhase(state, 1);
      if (blocked.length > 0 && state.currentPhase < 1) {
        ctx.ui.notify(`Phase 1 is gated:\n${blocked.map((b) => `· ${b}`).join("\n")}`, "error");
        return;
      }
      const count = parseInt(args?.trim() || "5", 10);
      let added = 0;
      for (let i = 0; i < count; i++) {
        const description = await ctx.ui.input(`Requirement ${i + 1}/${count}`, "");
        if (!description) break;
        const category = await ctx.ui.input("Category", "general");
        const res = addRequirement(state, { description, category });
        if (res.ok) added++;
        else ctx.ui.notify(res.message, "warning");
      }
      ctx.ui.notify(`[fleet] ${added} requirement(s) recorded.`, "info");
    },
  });

  pi.registerCommand("fleet:risks", {
    description: "Build the risk register (Phase 1)",
    handler: async (_args, ctx) => {
      const state = loadState();
      let added = 0;
      for (;;) {
        const title = await ctx.ui.input("Risk title (blank to finish)", "");
        if (!title) break;
        const likelihood = await ctx.ui.input("Likelihood (high/medium/low)", "medium");
        const impact = await ctx.ui.input("Impact (high/medium/low)", "medium");
        const mitigation = await ctx.ui.input("Mitigation", "");
        const res = addRisk(state, { title, likelihood: likelihood as any, impact: impact as any, mitigation });
        if (res.ok) added++;
      }
      ctx.ui.notify(`[fleet] ${added} risk(s) recorded.`, "info");
    },
  });

  pi.registerCommand("fleet:add-req", {
    description: "Manually add a requirement (/fleet:add-req <type> <description>)",
    handler: async (args, ctx) => {
      const parts = (args || "").trim().split(/\s+/);
      if (parts.length < 2) {
        ctx.ui.notify("Usage: /fleet:add-req <functional|non-functional> <description>", "warning");
        return;
      }
      const res = addRequirement(loadState(), {
        type: parts[0] === "non-functional" ? "non-functional" : "functional",
        description: parts.slice(1).join(" "),
      });
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
    },
  });

  pi.registerCommand("fleet:add-risk", {
    description: "Manually add a risk (/fleet:add-risk <title> — <description>)",
    handler: async (args, ctx) => {
      const raw = (args || "").trim();
      if (!raw) {
        ctx.ui.notify("Usage: /fleet:add-risk <title> — <description>", "warning");
        return;
      }
      const [title, ...rest] = raw.split(/\s+—\s+/);
      const res = addRisk(loadState(), { title, description: rest.join(" ") });
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
    },
  });

  pi.registerTool({
    name: "fleet_add_requirement",
    label: "Add Requirement",
    description:
      "Record a functional or non-functional requirement. Use this instead of writing 01_REQUIREMENTS.md by hand — the registry is the source of truth and Phase 1's gate reads it.",
    parameters: Type.Object({
      description: Type.String({ description: "What the system must do or guarantee" }),
      type: Type.Optional(
        Type.Union([Type.Literal("functional"), Type.Literal("non-functional")], {
          description: "Defaults to functional",
        })
      ),
      category: Type.Optional(Type.String({ description: "Grouping, e.g. storage, api, security" })),
      priority: Type.Optional(
        Type.Union(
          [Type.Literal("critical"), Type.Literal("high"), Type.Literal("medium"), Type.Literal("low")],
          { description: "Defaults to medium" }
        )
      ),
      source: Type.Optional(Type.String({ description: "Where the requirement came from" })),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addRequirement(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_add_risk",
    label: "Add Risk",
    description: "Record a risk against the architecture, with likelihood, impact, and mitigation.",
    parameters: Type.Object({
      title: Type.String({ description: "Short risk title" }),
      description: Type.Optional(Type.String()),
      likelihood: Type.Optional(
        Type.Union([Type.Literal("high"), Type.Literal("medium"), Type.Literal("low")])
      ),
      impact: Type.Optional(Type.Union([Type.Literal("high"), Type.Literal("medium"), Type.Literal("low")])),
      mitigation: Type.Optional(Type.String({ description: "How the risk is contained" })),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addRisk(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });
}