/**
 * fleet-tooling :: Phase 6 — Test Harnesses & Tooling
 *
 * Declares how each module or contract will actually be proven. A module with no
 * harness is an assumption, and Phase 11 integration is where assumptions bill.
 *
 * Commands: /fleet:tooling /fleet:harness
 * Tools:    fleet_add_harness, fleet_list_tooling
 *
 * Usage: pi -e extensions/fleet-tooling.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import {
  TOOL_FILE, archPath, ensureArchDir, loadState, saveState, audit, phaseBrief, aborted, ABORTED_RESULT } from "./fleet-core.ts";
import type { FleetState } from "./fleet-core.ts";
import { writeFileSync } from "node:fs";

// ─── Types ───────────────────────────────────────────────────────────────────

export const HARNESS_TYPES = [
  "unit", "integration", "contract", "end-to-end",
  "property", "fuzz", "benchmark", "load",
] as const;

export type HarnessType = (typeof HARNESS_TYPES)[number];

export interface ToolingItem {
  id: string;
  name: string;
  harnessType: HarnessType;
  targetModule: string;
  description: string;
  language: string;
  dependencies: string[];
  status: "planned" | "implemented" | "obsolete";
}

// ─── Operations ──────────────────────────────────────────────────────────────

function items(state: FleetState): ToolingItem[] {
  if (!state.tooling) state.tooling = [];
  return state.tooling as ToolingItem[];
}

export function addHarness(state: FleetState, input: Partial<ToolingItem>) {
  const list = items(state);
  if (!input.name?.trim()) return { ok: false, message: "name is required" };
  if (!input.targetModule?.trim()) {
    return { ok: false, message: "targetModule is required — a harness that targets nothing proves nothing" };
  }
  if (!HARNESS_TYPES.includes(input.harnessType as any)) {
    return { ok: false, message: `harnessType must be one of: ${HARNESS_TYPES.join(", ")}` };
  }

  const id = input.id?.trim() || `TOL-${String(list.length + 1).padStart(3, "0")}`;
  if (list.some((t) => t.id === id)) return { ok: false, message: `${id} already exists` };

  const item: ToolingItem = {
    id,
    name: input.name.trim(),
    harnessType: input.harnessType as HarnessType,
    targetModule: input.targetModule.trim(),
    description: input.description?.trim() || "",
    language: input.language?.trim() || "",
    dependencies: input.dependencies || [],
    status: "planned",
  };
  list.push(item);
  saveState(state);
  writeToolingFile(state);
  audit(`harness ${id} ${item.harnessType} -> ${item.targetModule}`, state);
  return { ok: true, message: `${id} ${item.harnessType} harness for ${item.targetModule}` };
}

/** Modules declared in Phase 4 that have no harness yet. */
export function untestedTargets(state: FleetState): string[] {
  const covered = new Set(items(state).map((t) => t.targetModule));
  return (state.modules || []).map((m: any) => m.id).filter((id: string) => !covered.has(id));
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeToolingFile(state: FleetState) {
  ensureArchDir();
  const list = items(state);
  if (list.length === 0) {
    writeFileSync(archPath(TOOL_FILE), "# Tooling Plan\n\n*No harnesses planned yet.*\n", "utf8");
    return;
  }
  const lines = [
    "# Tooling Plan",
    "",
    `*Generated by fleet-tooling · ${new Date().toISOString()}*`,
    "",
    "| ID | Name | Type | Target | Language | Status |",
    "|---|---|---|---|---|---|",
  ];
  for (const t of list) {
    lines.push(`| ${t.id} | ${t.name} | ${t.harnessType} | ${t.targetModule} | ${t.language || "—"} | ${t.status} |`);
  }
  const missing = untestedTargets(state);
  lines.push("", "---", "");
  if (missing.length > 0) {
    lines.push("## Modules Without a Harness", "");
    lines.push("These are defined but unproven. Phase 11 will surface them.", "");
    for (const id of missing) lines.push(`- ${id}`);
    lines.push("");
  }
  for (const t of list) {
    lines.push(`## ${t.id} — ${t.name}`);
    lines.push("");
    lines.push(`**Harness Type:** ${t.harnessType}  **Target:** ${t.targetModule}  **Status:** ${t.status}`);
    lines.push("");
    lines.push(t.description || "_unspecified_");
    lines.push("");
    lines.push(`**Language:** ${t.language || "—"}`);
    lines.push("");
    lines.push("### Dependencies");
    if (t.dependencies.length) for (const d of t.dependencies) lines.push(`- ${d}`);
    else lines.push("_none_");
    lines.push("");
    lines.push("---", "");
  }
  writeFileSync(archPath(TOOL_FILE), lines.join("\n"), "utf8");
}

// ─── Extension ───────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    const brief = phaseBrief(loadState());
    if (!brief) return null;
    return { systemPrompt: `${ctx.getSystemPrompt()}\n\n${brief}` };
  });

  pi.registerCommand("fleet:tooling", {
    description: "Define test harnesses and tooling (Phase 6)",
    handler: async (_args, ctx) => {
      const state = loadState();
      for (;;) {
        const name = await ctx.ui.input("Harness name (blank to finish)", "");
        if (!name) break;
        const type = await ctx.ui.input(`Type (${HARNESS_TYPES.join("/")})`, "unit");
        const target = await ctx.ui.input("Target (MOD or FMT id)", "");
        const desc = await ctx.ui.input("Description", "");
        const res = addHarness(state, { name, harnessType: type as any, targetModule: target, description: desc });
        ctx.ui.notify(res.message, res.ok ? "info" : "error");
      }
      const missing = untestedTargets(state);
      if (missing.length > 0) {
        ctx.ui.notify(`Modules without a harness: ${missing.join(", ")}`, "warning");
      }
    },
  });

  pi.registerCommand("fleet:harness", {
    description: "Quick-add a harness (/fleet:harness <target> <type> <name>)",
    handler: async (args, ctx) => {
      const parts = (args || "").trim().split(/\s+/);
      if (parts.length < 3) {
        ctx.ui.notify(`Usage: /fleet:harness <target> <type> <name>\nTypes: ${HARNESS_TYPES.join(", ")}`, "warning");
        return;
      }
      const res = addHarness(loadState(), {
        targetModule: parts[0], harnessType: parts[1] as any, name: parts.slice(2).join(" "),
      });
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
    },
  });

  pi.registerTool({
    name: "fleet_add_harness",
    label: "Add Test Harness",
    description:
      "Declare a test harness for a module or contract. Use fleet_untested_targets to find what is still unproven.",
    parameters: Type.Object({
      name: Type.String(),
      targetModule: Type.String({ description: "MOD- or FMT- id under test" }),
      harnessType: Type.Union(HARNESS_TYPES.map((t) => Type.Literal(t) as any), {
        description: HARNESS_TYPES.join(" | "),
      }),
      description: Type.Optional(Type.String()),
      language: Type.Optional(Type.String()),
      dependencies: Type.Optional(Type.Array(Type.String())),
      id: Type.Optional(Type.String()),
    }),
    async execute(_id, params, signal, _onUpdate, ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const res = addHarness(loadState(), params as any);
      ctx.ui.notify(res.message, res.ok ? "info" : "error");
      return { content: [{ type: "text", text: res.message }], details: { ok: res.ok } };
    },
  });

  pi.registerTool({
    name: "fleet_untested_targets",
    label: "Untested Targets",
    description: "List modules that have been defined but have no harness planned against them.",
    parameters: Type.Object({}),
    async execute(_id, _params, signal, _onUpdate, _ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const state = loadState();
      const missing = untestedTargets(state);
      const text = missing.length === 0
        ? "Every defined module has a harness."
        : `Modules without a harness (${missing.length}): ${missing.join(", ")}`;
      return { content: [{ type: "text", text }], details: { missing } };
    },
  });

  pi.registerTool({
    name: "fleet_list_tooling",
    label: "List Tooling",
    description: "List every planned or implemented test harness.",
    parameters: Type.Object({}),
    async execute(_id, _params, signal, _onUpdate, _ctx) {
      if (aborted(signal)) return ABORTED_RESULT;
      const list = items(loadState());
      const text = list.length === 0
        ? "No harnesses planned."
        : list.map((t) => `${t.id} — ${t.name} [${t.harnessType}] → ${t.targetModule} (${t.status})`).join("\n");
      return { content: [{ type: "text", text }], details: { count: list.length } };
    },
  });
}